<?php 
$token = $this->Token()->getToken();

?>
<?php $this->placeholder('formContent')->captureStart();?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '用户名：',
	    'name' => 'username',
	    'placeholder' => '请输入用户名',
	    'type' => 'text'
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '真实姓名：',
	    'name' => 'realname',
	    'placeholder' => '请输入真实姓名',
	    'type' => 'text'
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '手机号：',
	    'name' => 'tel',
	    'placeholder' => '请输入手机号',
	    'type' => 'text'
	])?>
	
    <?=$this->partial('partial/admin/form/select/workyard/select-workyards.phtml', [
        'selectedId'  => null,
        'withDefualt' => true,
        'withWarnig'  => true,
    ])?>
    
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/form-modal.phtml', [
    'pageName' => 'UserAddModal',
    'pageTitle' => '新增用户',
    'modalSize'     => 'lg',
    'form_id'=>'form-add-user',
    'action'=>"/api/user/add?token=$token",
//     'beforeForm' => $this->placeholder('beforeForm'),
    'formContent' => $this->placeholder('formContent'),
])?>
