<?php 
use Api\Entity\UserEntity;

$where = $this->where;
$page  = $this->page;
$paginator = $this->User()->getPaginator($page, $where);
?>
<?php $this->placeholder('buttonGroup')->captureStart();?>
<?=$this->partial('partial/admin/button/single.phtml', [
    'type'  => 'primary',
    'title' => '新增管理员',
    'data_modal_open' => true,
    'data_modal_url' => '/user/addModal'
])?>
<?php $this->placeholder('buttonGroup')->captureEnd() ?>

<?php $this->placeholder('searchContent')->captureStart();?>
<?=$this->partial('partial/admin/form/select/workyard/select-workyards.phtml', [
    'selectedId'  => null,
    'withDefualt' => true,
    'defaultTitle'=> '全部工地',
    ])?>
<?php $this->placeholder('searchContent')->captureEnd() ?>


<?php $this->placeholder('table')->captureStart();?>
<table class="table table-striped jambo_table">
    <thead>
        <tr>
          <th >用户名</th>
          <th >所辖工地</th>
          <th >电话</th>
<!--           <th >邮箱</th> -->
          <th >姓名</th>
          <!-- <th >状态</th> -->
          <th >操作</th>
    	</tr>
    </thead>
      <tbody>
      	<?php if (count($paginator)) :?>
      		<?php foreach ($paginator as $UserEntity):?>
      		<?php 
      		$userID     = $UserEntity->getId();
      		$username   = $UserEntity->getUsername();
      		$workyard_id   = $UserEntity->getWorkyard_id();
      		$workyard_name = $this->Workyard()->getName($workyard_id);
      		$tel        = $UserEntity->getTel();
      		$realname   = $UserEntity->getRealName();
      		?>
      		<tr>
      		<td><?=$username?></td>
      		<td><?=$workyard_name?></td>
      		<td><?=$tel?></td>
      		<td><?=$realname?></td>
      		<td>
      		<div class="btn-group  btn-group-sm">
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '编辑',
                'data_modal_open' => true,
      		    'data_modal_url' => '/user/editModal/'.$userID, //string
            ])?>
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '重置密码',
                'data_modal_open' => true,
      		    'data_modal_url' => '/user/resetPasswordModal/'.$userID, //string
            ])?>
            </div>
      		</td>
            </tr>
      		<?php endforeach;?>
      	<?php endif;?>
      </tbody>
</table>
<?php $this->placeholder('table')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/table-page.phtml', [
    'pageName'      => 'UserListPage',
    'pageTitle'     => '工地管理员',
    'paginator'     => $paginator,
    'search'        => $where,
    'buttonGroup'   => $this->placeholder('buttonGroup'),
    'searchContent' => $this->placeholder('searchContent'),
    'table'         => $this->placeholder('table'),
])?>
