<?php 
$userID         = $this->userID;
$UserEntity     = $this->User()->getEntity($userID);
$username       = $UserEntity->getUsername();
?>

<?php $this->placeholder('formContent')->captureStart();?>
<p>用户名: <?=$username?></p>
<p>该用户密码即将重置，</p>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/static-form-modal.phtml', [
    'pageName' => 'UserResetPasswordModal',
    'pageTitle' => '重置密码',
    'form_id'=>'form-reset-password',
    'action'=>'/api/user/resetPassword/' . $userID,
    'canSubmit'=>true,
    'formContent' => $this->placeholder('formContent'),
])?>

