<?php $this->headTitle('订单返现');?>

<div class="page__head">
<?=$this->partial('application/cashback/cashtotal.phtml', ['cashTotal' => $this->cashback()->getTotalCash()])?>
</div>

<div class="page__bd">

	<!-- paginator list -->
	<?php if (count($this->paginator)){?>
		<div class="weui-cells__title">领取金额(每月领取一次)</div>
	<div class="mypaginator" id="mypaginator">
    		<?=$this->partial('application/cashback/paginator.phtml', ['paginator' => $this->paginator,])?>
    	</div>
    <?php }else {?>
    	<?=$this->partial('partial/admin/defualt/gotohall.phtml')?>
    <?php }?>
	<!-- /paginator list -->
</div>

<!-- load more -->
<?=$this->partial('partial/admin/load/loadmore.phtml')?>
<!-- /load more -->

<!-- toast-->
<?=$this->partial('partial/admin/feedback/toast.phtml')?>
<!-- /toast-->

<div class="myhidden config">
	<input type="hidden" name="menu" value="领取金额">
</div>

<!-- import js -->
<script type="text/javascript" src="/js/service/Paginator.js"></script>
<script type="text/javascript" src="/js/service/Toast.js"></script>
<script type="text/javascript" src="/js/manager/point.js"></script>
<!-- /import js -->
