<!-- paginator -->
<?php foreach ($this->paginator as $item){?>
<div class="weui-form-preview">
	<div class="weui-form-preview__hd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">领取金额</label> <em
				class="weui-form-preview__value"><?=$this->cashback()->getCash($item)[0]?></em>
		</div>
	</div>
	<form action="" id="form_getcash" class="myhidden">
		<input type="hidden" value="<?=$item['id']?>" name="itemid"> <input
			type="hidden" value="<?=$this->cashback()->getCash($item)[0]?>"
			name="cashback"> <input type="hidden"
			value="<?=$this->cashback()->getCash($item)[1]?>" name="months"> <input
			type="hidden" value="<?=$this->cashback()->getCash($item)[2]?>"
			name="months_left">
	</form>
	<div class="weui-form-preview__bd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">商品</label> <span
				class="weui-form-preview__value"><?=$item['title']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">购买数量</label> <span
				class="weui-form-preview__value"><?=$item['num']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">所属订单</label> <span
				class="weui-form-preview__value"><?=$item['trade_id']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">订单总金额(含退款)</label> <span
				class="weui-form-preview__value">￥<?=$item['payment']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">返现总金额</label> <span
				class="weui-form-preview__value">￥<?=$item['cashback_total']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">已领取/总期数(月)</label> <span
				class="weui-form-preview__value"><?=$item['months_total'] - $item['months_left'] ?>&nbsp;/&nbsp;<?=$item['months_total']?></span>
		</div>
	</div>
	<div class="weui-form-preview__ft">
	    	<?php
    switch ($this->cashback()->getAction($item)) {
        case 'NEXT_MONTH_CAN_GET':
            echo "<span class='weui-form-preview__btn weui-form-preview__btn_default'>下月开始领取</span>";
            break;
        case 'ALREADY_GETED':
            echo "<span class='weui-form-preview__btn weui-form-preview__btn_default'>本月已领取</span>";
            break;
        case 'CAN_GET':
        default:
            echo "<a class='weui-form-preview__btn weui-form-preview__btn_primary btn_getcash' href='javascript:'>领取</a>";
    }
    ?>
	    </div>
</div>
<br />
<?php }?>
<!-- 分页导航-->
<?= $this->paginationControl($this->paginator);?>
<!-- /分页导航 -->
<!-- /paginator -->