<?php 
$title  = $this->Website()->getTitle();
?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- ico -->
	<?=$this->partial('layout/admin/partial/ico.phtml')?>
	<!-- /ico -->
    <?=$this->headTitle($title)->setSeparator(' - ') ?>

    <?=$this->partial('layout/admin/css/css.phtml')?>
</head>