<?php
use Api\Entity\PointEntity;

$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$where[PointEntity::FILED_WORKYARD_ID] = $workyard_id;
$PointEntities = $this->Point()->getEntities($where);

$WorkyardEntity = $this->Workyard()->getWorkyardEntity($workyard_id);
$workyard_name = $WorkyardEntity->getName();
$address = $WorkyardEntity->getAddress();
$desc = $WorkyardEntity->getNote();

$UserEntity = $this->User()->getEntityByIdentity($identity);
$userID = $UserEntity->getId();

$shift_id = $this->shift_id;
$done_count = $this->done_count;
?>

<div class="weui-popup__modal_content">
	<header class="demos-header">
			<h2 class="demos-second-title"><?=$workyard_name?></h2>
		</header>

		<div class="bd">
			<div class="page__bd">
				<div class="weui-cells__title">所有巡检点</div>
				<div class="weui-cells">
					<?php foreach ($PointEntities as $PointEntity) :?>
					<?php 
					$pointName = $PointEntity->getName();
					$address   = $PointEntity->getAddress();
					?>
					<div class="weui-cell">
						<div class="weui-cell__bd">
							<p><?=$pointName?></p>
						</div>
						<div class="weui-cell__ft"><small><?=date('Y-m-d H:i:s')?></small></div>
					</div>
					<?php endforeach;?>
				</div>
			</div>
		</div>

</div>
