<?php
use Api\Entity\PointEntity;

$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$where[PointEntity::FILED_WORKYARD_ID] = $workyard_id;
$PointEntities = $this->Point()->getEntities($where);

$WorkyardEntity = $this->Workyard()->getWorkyardEntity($workyard_id);
$workyard_name = $WorkyardEntity->getName();
$address = $WorkyardEntity->getAddress();
$desc = $WorkyardEntity->getNote();

$UserEntity = $this->User()->getEntityByIdentity($identity);
$userID = $UserEntity->getId();

$shift_id = $this->shift_id;
$done_count = $this->done_count;
?>

<div class="weui-popup__modal_content">
	<header class="demos-header">
		<h2 class="demos-second-title"><?=$workyard_name?></h2>
	</header>

	<div class="bd">
		<div class="weui-panel">
			<div class="weui-panel__hd">第1次巡检</div>
			<div class="weui-panel__bd">
				<?php foreach ($PointEntities as $PointEntity) :?>
					<?php 
					$pointName = $PointEntity->getName();
					$address   = $PointEntity->getAddress();
					?>
					<div class="weui-media-box weui-media-box_text">
					<h4 class="weui-media-box__title"><?=$pointName?></h4>
					<p class="weui-media-box__desc"><?=$address?></p>
					<ul class="weui-media-box__info">
						<li class="weui-media-box__info__meta">巡检时间<?=date('Y-m-d H:i:s')?></li>
					</ul>
				</div>
				<?php endforeach;?>
			</div>
		</div>
	</div>

</div>
