<?php
$title = $this->title;
$desc = $this->desc;

$website_title = $this->Website()->getTitle();
?>

<!DOCTYPE html>
<html lang="en">
  	<!-- include the head  -->
	<?=$this->partial('layout/admin/partial/head.phtml')?>
	<body class="nav-md error">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center text-center">
              <h1 class=""><?=$title?></h1>
              <h2><?=$desc?></h2>
              <a href="javascript:history.back();">返回上一页</a>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>
</body>
</html>
