<?php 
$shiftID     = $this->shiftID;
$ShiftEntity = $this->Shift()->getEntity($shiftID);
$shift_type_name = $ShiftEntity->getShift_type_name();
?>

<?php $this->placeholder('formContent')->captureStart();?>
<p>确认删除 <?=$shift_type_name?>?</p>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/delete-modal.phtml', [
    'pageName' => 'ShiftDeleteModal',
    'pageTitle' => '删除值班安排',
    'form_id'=>'form-delete-shift',
    'action'=>'/api/shift/delete/' . $shiftID,
    'canDelete'=>true,
    'formContent' => $this->placeholder('formContent'),
])?>
