<?php 
$shiftID     = $this->shiftID;
$ShiftEntity = $this->Shift()->getEntity($shiftID);
$start_time    = $ShiftEntity->getStart_time();
$start_time    = date('Y-m-d', $start_time);
//巡逻圈数和注意事项
$times = $ShiftEntity->getTimes();
$note = $ShiftEntity->getNote();
//所属工地
$workyard_id = $ShiftEntity->getWorkyard_id();
//班次
$shift_type_id = $ShiftEntity->getShift_type_id();

$token = $this->Token()->getToken();

?>

<?php $this->placeholder('formContent')->captureStart();?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '日期：',
	    'name' => 'date',
	    'placeholder' => '请选择时间',
	    'type' => 'text',
	    'value'=> $start_time,
	    'id' => 'datetimepicker'
	])?>
	<?=$this->partial('partial/admin/form/input/input-hide.phtml', [
        'name'  => 'shift_id',
	    'value' => $shiftID,
	])?>
	<?=$this->partial('partial/admin/form/select/shift_types/select-shift_types.phtml', [
	    'selectedId'  => $shift_type_id,
        'withDefualt' => true,
        'defaultTitle'=> '',
	    'workyard_id' => $workyard_id
     ])?>
     
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '巡检圈数：',
	    'name' => 'times',
	    'value'=> $times,
	    'placeholder' => '请输入巡检圈数',
	    'type' => 'text'
	])?>
		
    <?=$this->partial('partial/admin/form/textarea.phtml', [
        'id'    => '',
        'label' => '具体信息：',
        'name' => 'note',
        'value' => $note,
        'placeholder' => '选填：备注信息',
	])?>
    <?=$this->partial('partial/admin/form/select/user/select-multiple-guards.phtml', [
        'shiftID' => $shiftID,
     ])?>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/form-modal.phtml', [
    'pageName' => 'ShiftEditModal',
    'pageTitle' => '编辑值班安排',
    'modalSize'     => 'lg',
    'form_id'=>'form-edit-shift',
    'action'=>"/api/shift/edit/$shiftID?token=$token",
    'beforeForm' => $this->placeholder('beforeForm'),
    'formContent' => $this->placeholder('formContent'),
])?>
