<?php 
$where     = $this->where;
$page      = $this->page;
$identity  = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$paginator   = $this->Shift()->getPaginator($workyard_id, $page, $where);
?>
<?php $this->placeholder('buttonGroup')->captureStart();?>
<?=$this->partial('partial/admin/button/single.phtml', [
    'type'  => 'primary',
    'title' => '新增',
    'data_modal_open' => true,
    'data_modal_url' => '/shift/addModal'
])?>
<?php $this->placeholder('buttonGroup')->captureEnd() ?>

<?php $this->placeholder('searchContent')->captureStart();?>
<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '选择时间段：',
	    'name' => 'range',
	    'placeholder' => '请选择时间',
	    'type' => 'text',
	    'value'=> "",
	    'id' => 'select-range-date'
	])?>

<!-- 选择巡检员 -->
<?=$this->partial('partial/admin/form/select/guard/select-guards.phtml', [
 'selectedId'  => null,
 'withDefualt' => true,
 'defaultTitle'  => '全部',
 ])?>
<?php $this->placeholder('searchContent')->captureEnd() ?>

<?php $this->placeholder('table')->captureStart();?>
<table class="table table-striped jambo_table">
    <thead>
        <tr>
          <th >日期</th>
          <th >班次</th>
          <th >值班时间</th>
          <th >巡逻次数</th>
          <th >值班人员</th>
          <th >备注</th>
          <th >操作</th>
    	</tr>
    </thead>
      <tbody>
      	<?php if (count($paginator)) :?>
      		<?php foreach ($paginator as $Entity):?>
      		<?php 
      		$shiftID = $Entity->getId();
//       		$workyard_id   = $Entity->getWorkyard_id();
      		$shift_type_name = $Entity->getShift_type_name();
      		$start_time      = $Entity->getStart_time();
      		$end_time        = $Entity->getEnd_time();
      		$times           = $Entity->getTimes();
      		$note            = $Entity->getNote();
      		
      		$start_day   = date('Y-m-d', $start_time);
      		$is_next_day = $this->Shift()->isNextDay($start_time, $end_time);
      		$format_start_time = date('H:i', $start_time);
      		$format_end_time   = date('H:i', $end_time);
      		
//       		$format_end_time  = $is_next_day ? $format_end_time . "（次日+1）" : $format_end_time;
      		//获取值班人员
      		$guardNames = $this->ShiftGuard()->getGuardNamesByShiftId($shiftID);
      		?>
      		<tr>
      		<td><?=$start_day?></td>
      		<td>
      			<?=$shift_type_name?>
      		</td>
      		<td>
      			<?=$format_start_time?> - <?=$format_end_time?><small><?=$is_next_day ? '（次日+1）' : ''?></small>
      		</td>
      		<td><?=$times?>&nbsp;<small>次</small></td>
      		<td><?=$guardNames?></td>
      		<td><?=$note?></td>
      		<td>
      		<div class="btn-group  btn-group-sm">
      		<?php if ($start_time > time()) :?>
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '编辑',
                'data_modal_open' => true,
      		    'data_modal_url' => '/shift/editModal/'.$shiftID, //string
            ])?>
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '删除',
                'data_modal_open' => true,
      		    'data_modal_url' => '/shift/deleteModal/'.$shiftID, //string
            ])?>
      		<?php endif;?>
      		
            </div>
      		</td>
            </tr>
      		<?php endforeach;?>
      	<?php endif;?>
      </tbody>
</table>
<?php $this->placeholder('table')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/table-page.phtml', [
    'pageName'      => 'ShiftListPage',
    'pageTitle'     => '值班安排',
    'paginator'     => $paginator,
    'search'        => $where,
    'buttonGroup'   => $this->placeholder('buttonGroup'),
    'searchContent' => $this->placeholder('searchContent'),
    'table'         => $this->placeholder('table'),
])?>
