<?php
$ShiftEntity = $this->ShiftEntity;

$shift_id = $ShiftEntity->getId();
$note = $ShiftEntity->getNote();
$times = (int) $ShiftEntity->getTimes();
$times = (int) $times;
$shift_type_name = $ShiftEntity->getShift_type_name();
$start_time = $ShiftEntity->getStart_time();
$end_time = $ShiftEntity->getEnd_time();
?>
<div class="weui-form-preview">
	<div class="weui-form-preview__hd">
		<label class="weui-form-preview__label">日期</label> <em
			class="weui-form-preview__value"><?=date('Y-m-d', $start_time)?></em>
	</div>
	<div class="weui-form-preview__bd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">班次</label> <span
				class="weui-form-preview__value"><?=$shift_type_name?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">开始时间</label> <span
				class="weui-form-preview__value"><?=date('Y-m-d H:i', $start_time)?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">结束时间</label> <span
				class="weui-form-preview__value"><?=date('Y-m-d H:i', $end_time)?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">任务描述</label> <span
				class="weui-form-preview__value"><?=$note ? $note : '-'?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">巡逻次数</label> <span
				class="weui-form-preview__value"><?=$times?></span>
		</div>
	</div>
	<div class="weui-form-preview__ft">
		<a
			class="weui-form-preview__btn weui-form-preview__btn_primary open-popup"
			data-target="#popup-show-all-points" href="javascript:">查看巡逻点</a>
	</div>
</div>
