<?php
use Api\Entity\PointEntity;

$shift_id       = $this->shift_id;
$shift_time_id  = $this->shift_time_id;
$workyard_id    = $this->workyard_id;
$count          = $this->count;

//get all points
//created before shfit start time
$PointEntities = $this->Point()->getEntitiesOnShift($workyard_id, $shift_id);

?>
<div class="panel panel-info">
	<div class="panel-heading">
		<span>
		<i class="fa fa-navicon"></i> 
		第<?=$count?>次巡检记录</span> 
		<a class="pull-right panel-collapse-link" href="javascript:;">
		<i class="fa fa-chevron-up"></i></a>
	</div>
	<!-- 巡检点 -->
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>巡检点</th>
				<th>地址</th>
				<th>巡检时间</th>
				<th>备注</th>
				<th>是否巡检</th>
			</tr>
		</thead>
		<tbody>
    	<?php foreach ($PointEntities as $key=>$PointEntity) :?>
        <?php
            $point_id    = $PointEntity->getId();
            $pointName   = $PointEntity->getName();
            $address     = $PointEntity->getAddress();
            
            // 该巡检点巡检信息
            $ShiftTimePointEntity = $this->ShiftTimePoint()->getEntity($shift_time_id, $point_id);
            $has_done = !empty($ShiftTimePointEntity->getId());
            $time = $ShiftTimePointEntity->getTime();
            $note = $ShiftTimePointEntity->getNote();
            
            $time = $time ? date('Y-m-d H-i-s', $time) : null;
            ?>
        	<tr>
				<td><?=++$key?></td>
				<td><?=$this->escapehtml($pointName)?></td>
				<td><?=$this->escapehtml($address)?></td>
				<td><?=$this->escapehtml($time)?></td>
				<td><?=$this->escapehtml($note)?></td>
				<td>
            	<?php if($has_done):?>
            	<span class="text-success"><i class="fa fa-check"></i> 已巡检</span>
            	<?php else :?>
            	<span class="text-danger">未巡检</span>
            	<?php endif;?>
            	</td>
			</tr>
        <?php endforeach;?>
	  </tbody>
	</table>
	<!-- map -->
	<br>
	<div class="panel-body">
	<!-- 巡检轨迹 -->
	<h5 class="">巡检轨迹</h5>
	<div id="map_container" style="min-height: 500px; max-width: none;"></div>
	</div>
</div>

