<?php
use Api\Entity\PointEntity;

$shift_id       = $this->shift_id;
$shift_time_id  = $this->shift_time_id;
$workyard_id    = $this->workyard_id;
$count          = $this->count;

//get all points
//created before shfit start time
$PointEntities = $this->Point()->getEntitiesOnShift($workyard_id, $shift_id);
$address_path_json = $this->ShiftTimePoint()->getAddressPathJsonBy($shift_time_id);
?>
<div class="panel panel-info">
	<div class="panel-heading">
		<span>
		<i class="fa fa-navicon"></i> 
		第<?=$count?>次巡检记录</span> 
		<a class="pull-right panel-collapse-link" href="javascript:;">
		<i class="fa fa-chevron-up"></i></a>
	</div>
	<!-- 巡检点 -->
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>巡检点</th>
				<th>地址</th>
				<th>巡检时间</th>
				<th>备注</th>
				<th>是否巡检</th>
			</tr>
		</thead>
		<tbody>
    	<?php foreach ($PointEntities as $key=>$PointEntity) :?>
        <?php
            $point_id    = $PointEntity->getId();
            $pointName   = $PointEntity->getName();
            $address     = $PointEntity->getAddress();
            
            // 该巡检点巡检信息
            $ShiftTimePointEntity = $this->ShiftTimePoint()->getEntity($shift_time_id, $point_id);
            $has_done = !empty($ShiftTimePointEntity->getId());
            $time = $ShiftTimePointEntity->getTime();
            $note = $ShiftTimePointEntity->getNote();
            $address_path = $ShiftTimePointEntity->getAddress_path();
            $time = $time ? date('Y-m-d H:i:s', $time) : '-';
            $note = $note ? $note : '-';
            ?>
        	<tr data-address-path="<?=$address_path?>">
				<td><?=++$key?></td>
				<td class="point-name"><?=$this->escapehtml($pointName)?></td>
				<td><?=$this->escapehtml($address)?></td>
				<td class="point-time"><?=$this->escapehtml($time)?></td>
				<td class="point-note"><?=$this->escapehtml($note)?></td>
				<td>
            	<?php if($has_done):?>
            	<span class="text-success"><i class="fa fa-check"></i> 已巡检</span>
            	<?php else :?>
            	<span class="text-danger">未巡检</span>
            	<?php endif;?>
            	</td>
			</tr>
        <?php endforeach;?>
	  </tbody>
	</table>
	<!-- map -->
	<div class="panel-body">
		<div class="ln_solid"></div>
	<!-- 巡检轨迹 -->
		<div class="my-map">
        	<h5 class="">第<?=$count?>次巡检轨迹</h5>
        	<button type="button" class="btn btn-default show-map-track">巡检轨迹</button>
        	<button type="button" class="btn btn-default hide-map-track">关闭轨迹</button>
        	<div 
        	id="map_container_<?=$count?>" 
        	class="hide map-container" 
        	data-address-path=<?=$address_path_json?>
        	style="min-height: 500px;max-width: none;">
            </div>
    	</div>
	</div>
</div>

