<?php

/* <?=$this->partial('partial/admin/form/select/shift/select-whether_done.phtml', [
 ])?> */

?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"
		for="first-name">是否完成：</label>
	<div class="col-md-6 col-sm-6 col-xs-12">
    	<select 
    	name="done" 
    	class="form-control" 
    	>
    	<option value="not_done" selected="selected">未完成</option>
    	<option value="done">已完成</option>
		</select>
	</div>
</div>
