<?php
$form_id    = $this->form_id;
$action     = $this->action;
$formContent= $this->formContent;
$withBack   = $this->withBack;

/* <?=$this->partial('partial/admin/form/form/form.phtml', [
    'action'        => '',
    'form_id'       => '',
    'formContent'   => '',
	])?> */
?>

<form 
    class="form-ajax-submit form-horizontal form-label-left"
    id = "<?=$form_id?>"
    action="<?=$action?>"
    method="post"
    >
    	<?=$formContent?>
    	<div class="ln_solid"></div>
    	<div class="form-group">
    		<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3">
    			<?php if ($withBack === true) :?>
    			<button class="btn btn-default" type="button" onclick="history.back()">返回</button>
    			<?php endif;?>
    			<button class="btn btn-primary" type="reset">重置</button>
    			<button type="submit" class="btn btn-success">提交保存</button>
    		</div>
    	</div>
</form>