<?php
$identity   = $this->identity();
$UserEntity = $this->User()->getEntity(null, $identity);
$userID     = $UserEntity->getId();

$token = $this->Token()->getToken();

?>
<?php $this->placeholder('formContent')->captureStart();?>

<?=$this->partial('partial/admin/form/input/input.phtml', [
    'type'      => 'password',
    'label'     => '原密码：',
    'name'      => 'password_old',
    'value'     => '',
    'placeholder' => '请输入原密码',
 ])?>
<?=$this->partial('partial/admin/form/input/input.phtml', [
    'type'      => 'password',
    'label'     => '新密码：',
    'name'      => 'password',
    'value'     => '',
    'placeholder' => '请输入新密码',
 ])?>
<?=$this->partial('partial/admin/form/input/input.phtml', [
    'type'      => 'password',
    'label'     => '原密码：',
    'name'      => 'password_repeat',
    'value'     => '',
    'placeholder' => '请再次输入新密码',
 ])?>
 
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/form-page.phtml',[
    'pageName'  => 'AccountChangePasswordPage',
    'pageTitle' => '修改密码',
    'form_id'   =>'form-account-password',
    'action'=>"/api/user/changePassword/$userID?token=$token",
    'withBack'  => false,
    'formContent' => $this->placeholder('formContent'),
    
 ])?> 
