<?php
$selectedId     = $this->selectedId;
$withDefualt    = $this->withDefualt;
$defaultTitle   = $this->defaultTitle ? $this->defaultTitle : '请选择...';
$disabled       = $this->disabled;
$WorkyardEntities = $this->Workyard()->getEntities();

/* <?=$this->partial('partial/admin/form/select/workyard/select-workyards.phtml', [
 'selectedId'  => null,
 'withDefualt' => true,
 'defaultTitle'=> '',
 'disabled'=> '',
 ])?> */

?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"
		for="first-name">所属工地：</label>
	<div class="col-md-6 col-sm-6 col-xs-12">
    	<select 
    	name="workyard_id" 
    	class="form-control" 
    	<?=$disabled == true ? 'disabled' : '' ?>
    	>
			<?php if ($withDefualt) :?>
		    	<option value=''><?=$defaultTitle?></option>
		    <?php endif;?>
			<?php if (count($WorkyardEntities)) :?>
				<?php foreach ($WorkyardEntities as $WorkyardEntity) :?>
					<?php 
					$workyardID = $WorkyardEntity->getId();
					$name       = $WorkyardEntity->getName();
					?>
					<?php if ($selectedId === $workyardID) :?>
					<option value=<?=$workyardID?> selected="selected"><?=$name?></option>
					<?php else :?>
					<option value=<?=$workyardID?>><?=$name?></option>
					<?php endif;?>
				<?php endforeach;?>
			<?php endif;?>
	</select>
	<?php if (empty(count($WorkyardEntities))) :?>
	<a href="/workyard" class="text-danger">请先增加工地</a>
    <?php endif;?>
	</div>
</div>
