<?php 
$identity    = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$UserEntity  = $this->User()->getEntityByIdentity($identity);
$userID = $UserEntity->getId();

//获取某一巡逻员是否有值班安排
$has_shifts_on_plan = $this->ShiftGuard()->hasShiftsOnPlan($userID, $workyard_id);

//test
// $has_shifts_on_plan = [];

?>

<!-- 顶部导航 -->
<?php $this->placeholder('narbar')->captureStart();?>
<?=$this->partial('guard/shift/partial/top-narbar.phtml', [
    'search'=> '?type=plan'
])?>
<?php $this->placeholder('narbar')->captureEnd();?>

<?php $this->placeholder('content')->captureStart();?>

<?php if($has_shifts_on_plan) :?>
<div 
id="my-shifts-on-play" 
class="my-infinite"
>
<!-- 显示值班安排 -->
<?=$this->partial('guard/shift/partial/plan/paginator.phtml', [
    'user_id' => $userID,
    'workyard_id' => $workyard_id,
])?>

<?=$this->partial('partial/weixin/loading/loading.phtml')?>
<?=$this->partial('partial/weixin/loading/loading-done.phtml')?>

<!-- 显示所有巡逻点popup -->
<?=$this->partial('partial/weixin/popup/points.phtml', [
    'workyard_id' => $workyard_id
])?>

</div>

<!-- 无值班任务和安排 -->
<?php else :?>
<?=$this->partial('partial/weixin/empty/weui-msg.phtml', [
    'title' => '没有记录',
//     'desc' => '没有值班安排',
])?>
<?php endif;?>

<?php $this->placeholder('content')->captureEnd();?>

<?=$this->partial('partial/weixin/page/basic-page.phtml', [
    'pageName'    => 'ShiftPlanAndDonePage',
    'pageTitle'   => '值班安排',
    'narbar'     => $this->placeholder('narbar'),
    'content'     => $this->placeholder('content'),
])?>
