<?php
/**
 * 计划安排的值班任务
 */
$workyard_id = $this->workyard_id;
$user_id = $this->user_id;
$page = $this->page;

$ShiftPaginator = $this->ShiftGuard()->getPaginatorOnPlan($workyard_id, $user_id, $page);
$page_current   = $ShiftPaginator->getCurrentPageNumber();
$page_count     = $ShiftPaginator->count();

?>

<div class="weui-cells__title">值班安排</div>
<div 
class="my-infinite-list"
data-workyard-id = "<?=$workyard_id?>"
data-user-id = "<?=$user_id?>"
data-type = "plan"
>
<?php foreach ($ShiftPaginator as $ShiftEntity):?>
<div 
class="my-infinite-list-cell"
data-page-current="<?=$page_current?>"
data-page-count="<?=$page_count?>"
>
<?=$this->partial('partial/weixin/preview/sfhit-plan.phtml', [
    'ShiftEntity' =>$ShiftEntity
])?>
</div>
<?php endforeach;?>
</div>
