<?php
$title = $this->Website()->getTitle();
$token = $this->Token()->getToken();
$openid = $this->openid;
?>
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <?=$this->headTitle("工地注册-$title") ?>

    <?=$this->partial('layout/weixin/css/css.phtml')?>
</head>
<body ontouchstart="">
	<div class="container"> 
		<div class="page" data-name="RegisterPage">
    	<header class='demos-header'>
    		<h2 class="demos-title">工地注册</h2>
    	</header>
    	<form 
    	action="/api/register?token=<?=$token?>" 
    	class="form-ajax-submit" 
    	id="form-register"
    	method="post"
    	>
    		<div class="weui-cells__title">工地信息</div>
        	<div class="weui-cells ">
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'workyard_name',
                    'placeholder'=>'工地名称',
                  ]);?>
                  
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'workayrd_address',
                    'placeholder'=>'工地地址',
                  ]);?>
        	</div>
    		<div class="weui-cells__title">工地联系人</div>
        	<div class="weui-cells ">
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'admin_realname',
                    'placeholder'=>'联系人姓名',
                  ]);?>
                  
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'admin_tel',
                    'placeholder'=>'联系人电话',
                  ]);?>
        	</div>
        	<input type="hidden" name="admin_openid" value="<?=$openid?>">
        	<?=$this->partial('partial/weixin/button/submit.phtml', [
                'title' => '提交注册',
            ])?>
    	</form>
    	
    	</div>
    	<?=$this->partial('layout/weixin/partial/footer.phtml')?>
	</div>
	<?=$this->partial('layout/weixin/js/init.phtml')?>
</body>
</html>
