<?php $this->headTitle('提现记录');?>
<div class="page__head">
    <?=$this->partial('application/cashback/cashtotal.phtml', ['cashTotal' => $this->cashback()->getTotalCash()])?>
</div>

<div class="page__bd">
	<?php if (count($this->paginator)){?>
    	<div class="weui-cells__title">提现记录：</div>
	<div class="mypaginator" id="mypaginator">
		<!-- paginator list -->
        	<?=$this->partial('application/withdraw/paginator.phtml', ['paginator' => $this->paginator])?>
        	<!-- /paginator list -->
	</div>
    <?php }else {?>
    	<?=$this->partial('partial/admin/defualt/empty.phtml')?>
    <?php }?>
</div>
<div class="myhidden config">
	<input type="hidden" name="menu" value="提现记录">
</div>
<!-- load more -->
<?=$this->partial('partial/admin/load/loadmore.phtml')?>
<!-- /load more -->

<script type="text/javascript" src="/js/service/Paginator.js"></script>
<script type="text/javascript" src="/js/manager/withdraw_history.js"></script>
