<!-- paginator -->
<?php foreach ($this->paginator as $item){?>
<div class="weui-form-preview">
	<div class="weui-form-preview__hd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">提现状态</label> <em
				class="weui-form-preview__value status"><?=$this->cashback()->getStatusOfRemit($item['status'])?></em>
		</div>
	</div>
	<div class="weui-form-preview__bd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">提现编号</label> <span
				class="weui-form-preview__value"><?=$item['withdraw_id']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">提现总金额</label> <span
				class="weui-form-preview__value"><?=$item['cashback_total']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">手续费</label> <span
				class="weui-form-preview__value"><?=$item['cashback_fee']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">实际提现</label> <span
				class="weui-form-preview__value"><?=$item['cashback_real']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">银行卡号</label> <span
				class="weui-form-preview__value"><?=$item['card_no']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">银行卡持有人</label> <span
				class="weui-form-preview__value"><?=$item['card_user_name']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">申请日期</label> <span
				class="weui-form-preview__value"><?=$item['created']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">打款日期</label> <span
				class="weui-form-preview__value"><?=$item['remit_time']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">备注</label> <span
				class="weui-form-preview__value"><?=$item['remit_note']?></span>
		</div>
	</div>
</div>
<br />
<?php }?>
<!-- 分页导航-->
<?= $this->paginationControl($this->paginator);?>
<!-- /分页导航 -->
<!-- /paginator -->
