<?php
$identity = $this->identity();
$UserEntity = $this->User()->getEntity(null, $identity);
$userID     = $UserEntity->getId();
?>

<?php $this->placeholder('narbar')->captureStart();?>
<?=$this->partial('guard/account/partial/top-narbar.phtml')?>
<?php $this->placeholder('narbar')->captureEnd();?>


<?php $this->placeholder('content')->captureStart();?>
<form 
action="<?='/api/user/changePassword/' . $userID?>" 
class="form-ajax-submit" 
id="form-account-password"
method="post"
>
	<div class="weui-cells ">
		<?=$this->partial('partial/weixin/form/input/input.phtml', [
            'name'=>'old_password',
            'placeholder'=>'确认原密码',
            'type'=>'password',
          ]);?>
		<?=$this->partial('partial/weixin/form/input/input.phtml', [
            'name'=>'password',
            'placeholder'=>'输入新密码',
            'type'=>'password',
          ]);?>
		<?=$this->partial('partial/weixin/form/input/input.phtml', [
            'name'=>'repeat_password',
            'placeholder'=>'再次输入新密码',
            'type'=>'password',
          ]);?>
	</div>
	<?=$this->partial('partial/weixin/button/submit.phtml', [
        'title' => '确认提交',
    ])?>
</form>
<?=$this->partial('layout/weixin/partial/footer.phtml')?>
<?php $this->placeholder('content')->captureEnd();?>

<?=$this->partial('partial/weixin/page/basic-page.phtml', [
    'pageName'    => 'ChangePasswordPage',
    'pageTitle'   => '修改密码',
    'narbar'     => $this->placeholder('narbar'),
    'tarbar'     => false,
    'content'     => $this->placeholder('content'),
])?>
