<?php
return [
    'trade_type'=>[
        'point'=>[
            '1'=>[
                'item_id'=>319947441,
                'the_lowest_payment'=>1500,
            ],
            '2'=>[
                'item_id'=>358695378,
                'the_lowest_payment'=>0,
            ],
            '3'=>[
                'item_id'=>358690053,
                'the_lowest_payment'=>0,
            ],
            '4'=>[
                'item_id'=>358206199,
                'the_lowest_payment'=>0,
            ],
            '5'=>[
                'item_id'=>357749156,
                'the_lowest_payment'=>0,
            ],
            '6'=>[
                'item_id'=>358204075,
                'the_lowest_payment'=>0,
            ],
            '7'=>[
                'item_id'=>357741449,
                'the_lowest_payment'=>0,
            ],
            '8'=>[
                'item_id'=>357738551,
                'the_lowest_payment'=>0,
            ],
        ],
        'seller'=>[
            '1'=>[
                'item_id'=>5992173,
                'the_lowest_payment'=>0,
            ],
        ],
    ],
    'types'=>[
        'point'=>[
            'date'=>[
                'start' =>strtotime('2017-06-08'),
                'end'   =>strtotime('2019-08-08'),
            ],
            'back'=>[
                'percent_cash'=>0.6,
                'months'=>22,
            ],
        ],
        //about point trade
        'seller'=>[
        ],
    ],
];
