<?php 
$search = $this->search;
$route  = $this->route;
$action = $this->action;

?>
<div class="row" data-search = "<?=count($this->search)?>">
	<div class="col-sm-5">
		<div 
		class="dataTables_info" 
		role="status" 
		aria-live="polite"
		>当前 <?=$this->currentItemCount?> 条数据，共  <?=$this->totalItemCount?> 条数据</div>
	</div>
	<div class="col-sm-7">
		<div class="dataTables_paginate paging_simple_numbers"
			aria-label="Page navigation">
			<ul class="pagination" style="margin: auto">
            <!-- 上一页 -->
            <?php if (isset($this->previous)): ?>
            		<?php 
            		$page = $this->previous;
					$query = $this->search;
					$query['page'] = $page;
					?>
                <li class="">
                    <a 
                    href="<?= $this->url($this->route,['action'=>$action],['query'=>$query],true); ?>"
            	    data-page = "<?=$page?>"
                    >上一页</a>
                </li> 
            <?php else: ?>
           	 	<li class="disabled"><a href="#">上一页</a></li>
            <?php endif; ?>
            
            <!-- 页码 -->
            <?php foreach ($this->pagesInRange as $page): ?>
				<?php if ($page != $this->current): ?>
					<?php 
					$query = $this->search;
					$query['page'] = $page;
					?>
                    <li class="">
                    	<a href="<?= 
                    	$this->url(
                    	    $this->route, 
                    	    ['action'=>$action], 
                    	    ['query'=>$query], 
                    	    true); ?>"
                	    data-page = "<?=$page?>"
                    	><?= $page; ?></a>
                    </li>
				<?php else: ?>
				    <!-- 当前页面 -->
					<li class="disabled"><a><?= $page; ?></a></li>
				<?php endif; ?>
			<?php endforeach; ?>
            <!-- 下一页 -->
			<?php if (isset($this->next)): ?>
					<?php 
					$query = $this->search;
					$query['page'] = $this->next;
					?>
				<li class="">
					<a href="<?= 
					$this->url(
					    $this->route,
					    ['action'=>$action],
					    ['query'=>$query],
                    	    true); ?>"
            	    data-page = "<?=$page?>"
					>
						<span>下一页</span>
					</a>
				</li>	
			<?php else: ?>
			<li class="disabled"><a href="#">下一页</a></li>
			<?php endif; ?>
        </ul>
		</div>
	</div>
</div>
