<div class="js_dialog" id="iosDialog2"
	style="opacity: 0; display: none;">
	<div class="weui-mask"></div>
	<div class="weui-dialog">
		<div class="weui-dialog__bd">
			<p>销售员业绩永不清零</p>
			<p>每月初根据销售员历史业绩总和计算出佣金比例和佣金总额；</p>
			<p>本次实发佣金=佣金总额 - 历史已发佣金总和；</p>
		</div>
		<div class="weui-dialog__ft">
			<a href="javascript:;"class="weui-dialog__btn weui-dialog__btn_primary confirm">知道了</a>
		</div>
	</div>
</div>