<?php $this->headTitle('分销员奖金');?>
<div class="page__head">
	<!-- points all -->
    <?=$this->partial('application/point/points-total.phtml', ['amount' => $this->user()->getAmountOfUser()])?>
    <!-- /points all -->
	<!-- sabvar -->
    <?=$this->partial('application/partial/navbar-point-top.phtml')?>
    <!-- /sabvar -->
</div>

<div class="page__bd">
		<div class="weui-cells__title">
    		<a href="javascript:;" id="a_note_about_accure_points">分销员奖金</a>
    		<a href="<?=$this->seller_url?>" class="title_right">立返奖金</a>
		</div>
	<?php if (count($this->paginator)){?>
    	<div class="mypaginator" id="mypaginator">
    		<!-- paginator list -->
            	<?=$this->partial('application/commission/paginator.phtml', ['paginator' => $this->paginator])?>
            	<!-- /paginator list -->
    	</div>
    <?php }else {?>
    	<?=$this->partial('application/partial/defualt/empty.phtml')?>
    <?php }?>
</div>
<div class="myhidden config">
	<input type="hidden" name="menu" value="分销员奖金">
</div>
<!-- dialog-->
<?=$this->partial('application/commission/dialog.phtml')?>
<!-- /dialog-->

<!-- load more -->
<?=$this->partial('partial/admin/load/loadmore.phtml')?>
<!-- /load more -->

<script type="text/javascript" src="/js/service/Paginator.js"></script>
<script type="text/javascript" src="/js/manager/commission.js"></script>
