<?php 
$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
// $WorkyardEntity = $this->Workyard()->getWorkyardEntity($workyard_id);
// $workyard_name  = $WorkyardEntity->getName();
// $address_path = $WorkyardEntity->getAddress_path();

$token = $this->Token()->getToken();

?>

<?php $this->placeholder('formContent')->captureStart();?>
	
	<?=$this->partial('partial/admin/form/input/input-hide.phtml', [
        'name'  => 'created_by',
	    'value' => $identity,
	])?>
	
	<?=$this->partial('partial/admin/form/input/input-hide.phtml', [
        'name'  => 'workyard_id',
	    'value' => $workyard_id,
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '巡逻点名称：',
	    'name' => 'name',
	    'placeholder' => '请输入巡逻点名称',
	    'type' => 'text'
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '位置：',
	    'name' => 'address',
	    'placeholder' => '请输入位置',
	    'type' => 'text'
	])?>
	
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/form-modal.phtml', [
    'pageName'      => 'PointAddPage',
    'pageTitle'     => '新增巡逻点',
    'modalSize'     => 'lg',
    'form_id'       => 'form-add-point',
    'action'        => "/api/point/add?token=$token",
    'formContent'   => $this->placeholder('formContent'),
])?> 
