<?php 
//获取point 信息
$point_id = $this->pointID;
$PointEntity = $this->Point()->getEntity($point_id);
$name = $PointEntity->getName();
$address= $PointEntity->getAddress();
$workyard_id = $PointEntity->getWorkyard_id();
$canDelete   = $this->Point()->canDelete($point_id, $workyard_id);

$token = $this->Token()->getToken();
?>

<?php $this->placeholder('formContent')->captureStart();?>
<?php if($canDelete):?>
<p>巡逻点：<?=$name?></p>
<p>确认删除 ?</p>
<?php else :?>
<p>当前巡逻任务包含此巡逻点，不可删除！</p>
<p>当巡逻任务结束或未开始之前可删除巡逻点。</p>
<?php endif;?>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/delete-modal.phtml', [
    'pageName' => 'PointDeletePage',
    'pageTitle' => '删除巡逻点',
    'form_id'=>'form-delete-point',
    'action'=>"/api/point/delete/$workyard_id/$point_id?token=$token",
    'canDelete'=>$canDelete,
    'formContent' => $this->placeholder('formContent'),
])?>
