<?php
//获取point 信息
$point_id = $this->pointID;
$PointEntity = $this->Point()->getEntity($point_id);
$name = $PointEntity->getName();
$address= $PointEntity->getAddress();
$workyard_id = $PointEntity->getWorkyard_id();

$token = $this->Token()->getToken();

?>

<?php $this->placeholder('formContent')->captureStart();?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '巡检点名称：',
	    'name' => 'name',
	    'placeholder' => '请输入巡检点名称',
	    'type' => 'text',
	    'value' => $name,
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '地址：',
	    'name' => 'address',
	    'placeholder' => '请输入地址',
	    'type' => 'text',
	    'value' => $address,
	])?>
	
	<?=$this->partial('partial/admin/form/input/input-hide.phtml', [
        'name'  => 'point_id',
	    'value' => $point_id,
	])?>
	
	<?=$this->partial('partial/admin/form/input/input-hide.phtml', [
        'name'  => 'workyard_id',
	    'value' => $workyard_id,
	])?>
	
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/form-modal.phtml', [
    'pageName'      => 'PointEditPage',
    'pageTitle'     => '编辑巡检点',
    'modalSize'     => 'lg',
    'form_id'       => 'form-edit-point',
    'action'        => "/api/point/edit/$workyard_id/$point_id?token=$token",
    'formContent'   => $this->placeholder('formContent'),
])?> 
