<div class="weui-tabbar">
    <a href="javascript:;" class="weui-tabbar__item weui-bar__item--on">
      <span class="weui-badge" style="position: absolute;top: -.4em;right: 1em;">8</span>
      <div class="weui-tabbar__icon">
        <i class="fa fa-home  weui-tabbar__label"></i>
      </div>
      <p class="weui-tabbar__label">巡检任务</p>
    </a>
    <a href="javascript:;" class="weui-tabbar__item scan-qrcode">
      <div class="weui-tabbar__icon">
        <i class="fa fa-camera-retro  weui-tabbar__label"></i>
      </div>
      <p class="weui-tabbar__label">扫码</p>
    </a>
    <a href="javascript:;" class="weui-tabbar__item">
      <div class="weui-tabbar__icon">
        <img src="./images/icon_nav_msg.png" alt="">
      </div>
      <p class="weui-tabbar__label">考勤</p>
    </a>
    <a href="javascript:;" class="weui-tabbar__item">
      <div class="weui-tabbar__icon">
        <img src="./images/icon_nav_cell.png" alt="">
      </div>
      <p class="weui-tabbar__label">我</p>
    </a>
  </div>