<div class="weui-tabbar">
	<a href="/" class="weui-tabbar__item"> 
	<!-- <span class="weui-badge" style="position: absolute; top: -.4em; right: 1em;">8</span> -->
		<div class="weui-tabbar__icon">
			<i class="fa fa-home  weui-tabbar__label"></i>
		</div>
		<p class="weui-tabbar__label">巡检任务</p>
	</a> 
	
<!-- 	<a href="javascript:;" class="weui-tabbar__item scan-qrcode"> -->
<!-- 		<div class="weui-tabbar__icon"> -->
<!-- 			<i class="fa  fa-reorder   weui-tabbar__label"></i> -->
<!-- 		</div> -->
<!-- 		<p class="weui-tabbar__label">扫描测试</p> -->
<!-- 	</a>  -->
	
	<a href="/shift" class="weui-tabbar__item">
		<div class="weui-tabbar__icon">
			<i class="fa  fa-reorder   weui-tabbar__label"></i>
		</div>
		<p class="weui-tabbar__label">值班安排</p>
	</a> 
	
	<a href="/account" class="weui-tabbar__item">
		<div class="weui-tabbar__icon">
			<i class="fa  fa-user   weui-tabbar__label"></i>
		</div>
		<p class="weui-tabbar__label">我</p>
	</a>
</div>