<!-- current page -->
<div class="myhidden">
	<input type="hidden" value="<?=$this->current?>" name="current_page"> <input
		type="hidden" value="<?=$this->next?>" name="next_page"> <input
		type="hidden" value="<?=empty($this->next) ? 'no' : 'yes' ?>"
		name=has_next>
</div>
<!-- /current page -->
<!-- 下一页 -->
<?php if (!isset($this->next)): ?>
<div class="weui-loadmore weui-loadmore_line">
	<span class="weui-loadmore__tips">已加载全部数据</span>
</div>
<?php endif; ?>
<!-- /下一页 -->
