<!-- Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<!-- My css  -->
<link href="/_admin/css/mycss.css" rel="stylesheet">
<link href="https://colorlib.com/polygon/vendors/animate.css/animate.min.css" rel="stylesheet">

<!-- Font Awesome -->
<link href="/_admin/vendors/font-awesome/css/font-awesome.min.css"
	rel="stylesheet">
	
<!-- NProgress -->
<link href="/_admin/vendors/nprogress/nprogress.css" rel="stylesheet">
<!-- jQuery custom content scroller -->

<!-- Custom Theme Style -->
<link href="/_admin/css/custom.min.css" rel="stylesheet">

<!-- Custom Theme Style -->
<link href="/_admin/vendors/jquery.mloading-master/src/jquery.mloading.css" rel="stylesheet">

<!-- bootstrapValidator -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/css/bootstrapValidator.min.css" rel="stylesheet">
<!-- pnotify -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.css" rel="stylesheet">

<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/all.css" rel="stylesheet"> -->

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.1/css/select2.min.css" rel="stylesheet">
