<?php 
use Api\Entity\UserEntity;

$page      = $this->page;
$where     = $this->where;
$identity  = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$paginator = $this->Guard()->getPaginator($workyard_id, $page, $where);
?>
<?php $this->placeholder('buttonGroup')->captureStart();?>
<?=$this->partial('partial/admin/button/single.phtml', [
    'type'  => 'primary',
    'title' => '新增',
    'data_modal_open' => true,
    'data_modal_url' => '/guard/addModal'
])?>
<?php $this->placeholder('buttonGroup')->captureEnd() ?>

<?php $this->placeholder('table')->captureStart();?>
<table class="table table-striped jambo_table">
    <thead>
        <tr>
          <th >用户名</th>
          <th >电话</th>
          <th >姓名</th>
          <th >操作</th>
    	</tr>
    </thead>
      <tbody>
      	<?php if (count($paginator)) :?>
      		<?php foreach ($paginator as $UserEntity):?>
      		<?php 
      		$userID     = $UserEntity->getId();
      		$username   = $UserEntity->getUsername();
      		$tel        = $UserEntity->getTel();
      		$realname   = $UserEntity->getRealName();
      		?>
      		<tr>
      		<td><?=$username?></td>
      		<td><?=$tel?></td>
      		<td><?=$realname?></td>
      		<td>
      		<div class="btn-group  btn-group-sm">
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '编辑',
                'data_modal_open' => true,
      		    'data_modal_url' => '/guard/editModal/'.$userID, //string
            ])?>
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '重置密码',
                'data_modal_open' => true,
      		    'data_modal_url' => '/guard/resetPasswordModal/'.$userID, //string
            ])?>
            </div>
      		</td>
            </tr>
      		<?php endforeach;?>
      	<?php endif;?>
      </tbody>
</table>
<?php $this->placeholder('table')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/table-page.phtml', [
    'pageName'      => 'UserListPage',
    'pageTitle'     => '工地巡逻员',
    'paginator'     => $paginator,
    'search'        => $where,
    'buttonGroup'   => $this->placeholder('buttonGroup'),
//     'searchContent' => $this->placeholder('searchContent'),
    'table'         => $this->placeholder('table'),
])?>
