<?php 
//获取point 信息
$workyardID = $this->workyardID;
$WorkyardEntity = $this->Workyard()->getWorkyardEntity($workyardID);
$name       = $WorkyardEntity->getName();

$token = $this->Token()->getToken();
?>

<?php $this->placeholder('formContent')->captureStart();?>
<p>确认删除？</p>
<p><?=$name?></p>
<p class="text-danger">会删除该工地管理员!</p>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/delete-modal.phtml', [
    'pageName' => 'WorkyardDeletePage',
    'pageTitle' => '删除工地',
    'form_id'=>'form-delete-workyard',
    'action'=> "/api/workyard/delete/$workyardID?token=$token",
    'canDelete'=>true,
    'formContent' => $this->placeholder('formContent'),
])?>
