<?php 
$workyardID = $this->workyardID;
$WorkyardEntity = $this->Workyard()->getWorkyardEntity($workyardID);
$name       = $WorkyardEntity->getName();
$note       = $WorkyardEntity->getNote();
$address    = $WorkyardEntity->getAddress();
$address_path = $WorkyardEntity->getAddress_path();
$token = $this->Token()->getToken();

?>
<?php $this->placeholder('formContent')->captureStart();?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '名称：',
	    'name' => 'name',
	    'placeholder' => '请输入工地名称',
	    'type' => 'text',
	    'value'=> $name,
	])?>
	<?=$this->partial('partial/admin/form/input/input-hide.phtml', [
        'name' => 'old_name',
	    'value' => $name,
	])?>
	<div class="form-group">
    	<label class="control-label col-md-3 col-sm-3 col-xs-12">具体地址：</label>
    	<div class="col-md-6 col-sm-6 col-xs-12">
    		<input 
    		type="text" 
    		name="address"
    		placeholder="输入工地地址"
    		value="<?=$address?>"
    		id = "tipinput"
    		class="form-control col-md-6 col-xs-12">
		</div>
    	<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3 col-xs-offset-12" id="">
        	<div id="map_container" style="min-height: 500px; max-width: none;"></div>
        	<div class="input-card">
        		<?php if(!empty($address_path)):?>
  	 			<button 
  	 			type="button"
  	 			class="btn btn-round btn-primary btn-xs" 
  	 			id ="button-edit-open"
  	 			>开始编辑</button> 
   				<button 
   				type="button"
   				class="btn btn-round btn-primary btn-xs"
   				id ="button-edit-close" 
   				style="margin-top: 12px">关闭编辑</button> 
   				<?php else :?>
   				<button 
  	 			type="button"
  	 			class="btn btn-round btn-primary btn-xs" 
  	 			id ="button-mouse-draw-start"
  	 			>绘制</button> 
   				<button 
   				type="button"
   				class="btn btn-round btn-primary btn-xs"
   				id ="button-mouse-draw-delete" 
   				style="margin-top: 12px">删除</button> 
   				<?php endif;?>
			</div>
			<input type="hidden" name="address_path" value=<?=$address_path?>>
    	</div>
    	<?php if(empty($address_path)):?>
    	<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3 col-xs-offset-12" id="">
    	<div class="alert alert-info my-alert-info" role="alert">
    		<p>开始绘制：点击绘制按钮， 在地图上点鼠标左键 创建点;</p> 
    		<p>完成绘制： 点击鼠标右键完成绘制</p> 
    		<p>重新绘制：点击删除按钮，然后重新绘制即可</p> 
    		</div>
    	</div>
    	<?php endif;?>
    </div>
    <?=$this->partial('partial/admin/form/textarea.phtml', [
        'id'    => '',
        'label' => '具体信息：',
        'name' => 'note',
        'value' => $note,
        'placeholder' => '选填：工地详细信息',
	])?>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?php $this->placeholder('formContent')->captureEnd() ?>
<?=$this->partial('partial/admin/page/page/form-page.phtml', [
    'pageName'      => 'WorkyardEditPage',
    'pageTitle'     => '编辑工地',
    'form_id'       => 'form-edit-workyard',
    'action'        => "/api/workyard/edit/$workyardID?token=$token",
    'navbar'        => '/workyard/addPage',
    'formContent'   => $this->placeholder('formContent'),
])?> 
