<?php
use Api\View\Helper\ShiftGuardHelper;

/**
 * 计划安排的值班任务
 */
$workyard_id = $this->workyard_id;
$user_id = $this->user_id;
$page = $this->page;
$type = ShiftGuardHelper::TYPE_PLAN;
$ShiftPaginator = $this->ShiftGuard()->getPaginator($workyard_id, $user_id, $type, $page);

$page_current = $ShiftPaginator->getCurrentPageNumber();
$page_count   = $ShiftPaginator->count();

?>

<div class="weui-cells__title">值班安排</div>
<div 
class="my-infinite-list"
data-workyard-id = "<?=$workyard_id?>"
data-user-id = "<?=$user_id?>"
data-type = "<?=$type?>"
>
<?php foreach ($ShiftPaginator as $ShiftEntity):?>
<?php
$shift_id = $ShiftEntity->getId();
$note = $ShiftEntity->getNote();
$times = (int) $ShiftEntity->getTimes();
$times = (int) $times;
$shift_type_name= $ShiftEntity->getShift_type_name();
$start_time = $ShiftEntity->getStart_time();
$end_time   = $ShiftEntity->getEnd_time();
?>
<div 
class="weui-form-preview my-infinite-list-cell"
data-page-current="<?=$page_current?>"
data-page-count="<?=$page_count?>"
>
	<div class="weui-form-preview__hd">
		<label class="weui-form-preview__label">班次</label> <em
			class="weui-form-preview__value"><?=$shift_type_name?></em>
	</div>
	<div class="weui-form-preview__bd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">开始时间</label> <span
				class="weui-form-preview__value"><?=date('Y-m-d H:i', $start_time)?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">结束时间</label> <span
				class="weui-form-preview__value"><?=date('Y-m-d H:i', $end_time)?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">任务描述</label> <span
				class="weui-form-preview__value"><?=$note ? $note : '-'?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">巡检次数</label> <span
				class="weui-form-preview__value"><?=$times?></span>
		</div>
	</div>
	<div class="weui-form-preview__ft">
        <a 
        class="weui-form-preview__btn weui-form-preview__btn_primary open-popup" 
        data-target="#popup-show-all-points"
        href="javascript:">查看巡检点</a>
    </div>
 </div>
<?php endforeach;?>
</div>
