<?php
// 当前巡检任务
$ShiftEntity = $this->ShiftEntity;
$userID= $this->userID;

?>
<div style=" margin-top: 20px">
<?php if(count($ShiftEntity)):?>
		<?php
		$shift_id = $ShiftEntity->getId();
        $note = $ShiftEntity->getNote();
        $times = (int)$ShiftEntity->getTimes();
        $times = (int)$times;
        $ShiftEntity_type_name = $ShiftEntity->getShift_type_name();
        $start_time = $ShiftEntity->getStart_time();
        $end_time = $ShiftEntity->getEnd_time();
        
        //当前shift已完成巡检次数
        $done_count = $this->ShiftTime()->getDoneCount($userID, $shift_id);
        //是否完成巡检
        $is_done = $done_count == $times;
        //当前应该执行的巡检次数
        $next_count = $is_done ? null : $done_count + 1;
        //下一次巡检是否已开始
        ?>
		<div class="weui-form-preview">
    		<div class="weui-form-preview__hd">
    			<label class="weui-form-preview__label">班次</label> <em
    				class="weui-form-preview__value"><?=$ShiftEntity_type_name?></em>
    		</div>
    		<div class="weui-form-preview__bd">
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">开始时间</label> <span
    					class="weui-form-preview__value"><?=date('Y-m-d H:i', $start_time)?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">结束时间</label> <span
    					class="weui-form-preview__value"><?=date('Y-m-d H:i', $end_time)?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">已巡检/总次数</label> <span
    					class="weui-form-preview__value"><?=$done_count?>/<?=$times?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">任务描述</label> <span
    					class="weui-form-preview__value"><?=$note ? $note : '-'?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">状态</label> 
    				<span 
    				class="weui-form-preview__value"
    				><?=$is_done ? '巡检完成' : '第' . $next_count . '次巡检中...'?></span>
    			</div>
    		</div>
		</div>
		
    <?php else :?>
    <div class="weui-panel__bd">
    		<div class="weui-media-box weui-media-box_text">
    			<h4 class="weui-media-box__title">今日无值班安排！</h4>
    		</div>
    	</div>
    <?php endif;?>
</div>
