<?php
use Api\Entity\PointEntity;

$shift_time_id =$this->shift_time_id;
$workyard_id = $this->workyard_id;
$where[PointEntity::FILED_WORKYARD_ID] = $workyard_id;
$PointEntities = $this->Point()->getEntities($where);
?>

<div style="margin-top: 0px; margin-bottom:60px">
    <div class="weui-cells__title">巡检点</div>
    <div class="weui-cells" style="margin-top: 0px">
        <?php foreach ($PointEntities as $PointEntity) :?>
        <?php
        $point_id  = $PointEntity->getId();
        $pointName = $PointEntity->getName();
        $address   = $PointEntity->getAddress();
        
        //该巡检点巡检信息
        $ShiftTimePointEntity = $this->ShiftTimePoint()->getEntity($shift_time_id, $point_id);
        $has_done = !empty($ShiftTimePointEntity->getId());
        $time = $ShiftTimePointEntity->getTime();
        $note = $ShiftTimePointEntity->getNote();
        
        $time = $time ? date('Y-m-d H-i-s', $time) : null;
        
//         $time = date('Y-m-d H-i-s');
//         $note ='一切正常，没有发现问题';
        ?>
          <a 
          class="weui-cell weui-cell_access alert-point-info" 
          href="javascript:;"
          data-point-address="<?=$address?>"
          data-point-time="<?=$time?>"
          data-point-note="<?=$note?>"
          >
            <div class="weui-cell__bd">
              <p><?=$pointName?></p>
            </div>
            <div class="weui-cell__ft">
            <?php if($has_done):?>
            <i class="weui-icon-success-no-circle"></i>
            <?php else :?>
           	 待巡检
            <?php endif;?>
            </div>
          </a>
        
        <?php endforeach;?>
    </div>
</div>
