<?php
use Api\Entity\PointEntity;

$workyard_id = $this->workyard_id;
$userID = $this->userID;

// 今天巡检任务
$shifts = $this->Shift()->getGuardShift($userID, $workyard_id);
$where[PointEntity::FILED_WORKYARD_ID] = $workyard_id;
$PointEntities = $this->Point()->getEntities($where);

?>
<div style="margin-bottom: 60px; margin-top: 20px">
<?php if(count($shifts)):?>
	<?php foreach ($shifts as $shift):?>
		<?php
		$shift_id = $shift->getId();
        $note = $shift->getNote();
        $times = (int)$shift->getTimes();
        $times = (int)$times;
        $shift_type_name = $shift->getShift_type_name();
        $start_time = $shift->getStart_time();
        $end_time = $shift->getEnd_time();
        
        //判断该巡检任务是否已完成
        //当前时间在巡检时间内
        $is_within_time = $start_time < time() && $end_time > time();
        //已过巡检时间
        $is_beyond_time = $end_time <= time();
        //未到巡检时间
        $is_before_time = $start_time >= time();
        
        //当前shift已完成巡检次数
        $done_count = $this->ShiftTime()->getDoneCount($userID, $shift_id);
        //是否完成巡检
        $is_done = $done_count == $times;
        //当前应该执行的巡检次数
        $next_count = $is_done ? null : $done_count + 1;
        //下一次巡检是否已开始
        ?>
		<div class="weui-form-preview">
    		<div class="weui-form-preview__hd">
    			<label class="weui-form-preview__label">班次</label> <em
    				class="weui-form-preview__value"><?=$shift_type_name?></em>
    		</div>
    		<div class="weui-form-preview__bd">
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">开始时间</label> <span
    					class="weui-form-preview__value"><?=date('Y-m-d H:i', $start_time)?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">结束时间</label> <span
    					class="weui-form-preview__value"><?=date('Y-m-d H:i', $end_time)?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">已巡检/总次数</label> <span
    					class="weui-form-preview__value"><?=$done_count?>/<?=$times?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">任务描述</label> <span
    					class="weui-form-preview__value"><?=$note ? $note : '-'?></span>
    			</div>
    			<div class="weui-form-preview__item">
    				<label class="weui-form-preview__label">状态</label> 
    				<span 
    				class="weui-form-preview__value"
    				>
    				<?php if ($is_within_time) :?>
    					<?php if($is_done):?>
    					已完成
    					<?php else :?>
    					第<?=$next_count?>次巡检中...
    					<?php endif;?>
    				<?php else :?>
    					<?=$is_done ? '已完成' : '未完成'?>
    				<?php endif;?>
    				</span>
    			</div>
    		</div>
    		<!-- 正在巡检时间内 -->
    		<?php if($is_within_time):?>
    		<div class="weui-form-preview__ft">
    			<a 
    			class="weui-form-preview__btn weui-form-preview__btn_default log-shift"
    			data-done-count = <?=$done_count?>
    			data-shift-id="<?=$shift_id?>"
    				href="javascript:">巡检记录</a>
    			<a type="button"
    				class="weui-form-preview__btn weui-form-preview__btn_primary"
    				data-next-count="<?=$next_count?>"
    				data-shift-id="<?=$shift_id?>"
    				href="javascript:">巡检点-扫描</a>
    		</div>
    		<?php endif;?>
    		
    		<!-- 已过巡检时间 -->
    		<?php if($is_beyond_time):?>
    		<div class="weui-form-preview__ft">
    			<a 
    			class="weui-form-preview__btn weui-form-preview__btn_default log-shift"
    			data-done-count = <?=$done_count?>
    			data-shift-id="<?=$shift_id?>"
    			href="javascript:">巡检记录</a>
    			<button type="button"
    				class="weui-form-preview__btn weui-form-preview__btn_default weui-btn_disabled">已结束</button>
    		</div>
    		<?php endif;?>
    		
    		<!-- 巡检未开始 -->
    		<?php if($is_before_time):?>
    		<div class="weui-form-preview__ft">
        		<a class="weui-form-preview__btn weui-form-preview__btn_default open-popup"
        		 data-target="#all-points"
        		 href="javascript:">巡检点</a>
    			<button type="button"
    				class="weui-form-preview__btn weui-form-preview__btn_default weui-btn_disabled"><?=date('H:i', $start_time)?> 开始巡检</button>
    		</div>
    		<?php endif;?>
		</div>
		<br>
		<?php endforeach;?>
		
    <?php else :?>
    <div class="weui-panel__bd">
    		<div class="weui-media-box weui-media-box_text">
    			<h4 class="weui-media-box__title">今日无值班安排！</h4>
    		</div>
    	</div>
    <?php endif;?>
</div>
