<div class="js_dialog" id="iosDialog1" style="display: none;">
	<div class="weui-mask"></div>
	<div class="weui-dialog">
		<div class="weui-dialog__hd">
			<strong class="weui-dialog__title">提现确认</strong>
		</div>
		<div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">提现金额：</label>
            	￥<span class="cashback"></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">手续费：</label>
            	￥<span class="cashback_rate"></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">银行卡号：</label>
                <span class="card_no"><?=$this->escapehtml($this->card['card_no'])?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">银行名称：</label>
                <span class="card_bank_name"><?=$this->escapehtml($this->card['card_bank_name'])?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">银行地区：</label>
                <span class="card_bank_area"><?=$this->escapehtml($this->card['card_bank_area'])?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">开户行：</label>
                <span class="card_bank_branch_name"><?=$this->escapehtml($this->card['card_bank_branch_name'])?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">卡片类型：</label>
                <span class="card_type_name"><?=$this->escapehtml($this->card['card_type_name'])?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">持卡人姓名：</label>
                <span class="card_user_name"><?=$this->escapehtml($this->card['card_user_name'])?></span>
            </div>
        </div>
		<div class="weui-dialog__ft">
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_default dialog_close dialog_close" id="">返回修改</a>
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_primary dialog_confirm"
				id="dialog_confirm">确认提交</a>
		</div>
	</div>
</div>
