<?php
use Zend\Paginator\Paginator;
/**
 * 适用于table页面活着带有分页的table页面
 *  */
$pageName   = $this->pageName; // string
$pageTitle  = $this->pageTitle; // string
$buttonGroup= $this->buttonGroup; // button html
$table      = $this->table; // table html
$paginator  = $this->paginator; // 
$searchContent = $this->searchContent;

//批量删除按钮
$batchEditButtons = $this->batchEditButtons;

/* used age 

<?=$this->partial('partial/admin/page/page/table-page.phtml', [
    'pageName'      => 'UserListPage',
    'pageTitle'     => '用户管理',
    'paginator'     => $paginator,
    'search'        => $where,
    'buttonGroup'   => $this->placeholder('buttonGroup'),
    'batchEditButtons'=> $this->placeholder('batchEditButtons'),
    'searchContent' => $this->placeholder('searchContent'),
    'table'         => $this->placeholder('table'),
])?> 

*/

?>

<?php $this->placeholder('x_content')->captureStart();?>
<?php if ($searchContent) :?>
<?=$this->partial('partial/admin/search/search.phtml', [
    'searchContent' => $searchContent,
])?>
<?php endif;?>
<div class="x_content">
		<!-- /table -->
    	<div class="table-responsive">
    		<?=$table?>
    		<?php if (empty(count($paginator))):?>
    		<div class="well">未查询到数据</div>
    		<?php endif;?>
    	</div>
    	<!-- /table -->
    	
    	<!-- /batchEditButtons -->
    	<?php if (!empty($batchEditButtons)):?>
    	<?=$batchEditButtons?>
        <?php endif;?>
        <!-- /batchEditButtons -->
        
        <!-- /navigation -->
    	<?=$this->partial('partial/admin/paginator/navigation.phtml', [
            'paginator' => $paginator,
    	    'where'     => $this->search,
        ])?>
</div>
<?php $this->placeholder('x_content')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/basic-page.phtml', [
    'panelTitle'    => $buttonGroup,
    'pageName'      => $pageName,
    'pageTitle'     => $pageTitle,
    'x_content'     => $this->placeholder('x_content'),
])?>
