<?php
$title = $this->Website()->getTitle();
?>
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <?=$this->headTitle($title)->setSeparator(' - ') ?>

    <?=$this->partial('layout/weixin/css/css.phtml')?>
</head>
<body ontouchstart="">
	<div class="container">
		<?=$this->content ?>
	</div>
	
	<?=$this->partial('layout/weixin/js/init.phtml')?>
</body>
</html>