<?php
$Entities = $this->Workyard()->getEntities();
?>
<?php if(count($Entities)) :?>
<div class="col-md-3 col-sm-3 col-xs-12 profile_left">
	<ul 
	id ="workyard_info"
	class="list-unstyled user_data list-group"
	style="max-height: 600px; overflow: auto">
		<?php foreach ($Entities as $Entity):?>
    	<?php
            $name = $Entity->getName();
            $address = $Entity->getAddress();
            $note    = $Entity->getNote();
            $address_path = $Entity->getAddress_path();
        ?>
    	<li data-address-path=<?=$address_path?>>
    		<a href="javascript:;" class="list-group-item">
            	<h4 class="list-group-item-heading"><?=$name?></h4>
            	<p class="list-group-item-text"><?=$address?></p>
            	<br />
            	<p class="list-group-item-text"><?=$note?></p>
          	</a>
		</li>
    	<?php endforeach;?>
	</ul>
</div>

<div class="col-md-9 col-sm-9 col-xs-12">
	<div id="map_container" style="min-height: 600px; max-width: none;"></div>
</div>
<?php else :?>
<div class="col-md-12 col-sm-12 col-xs-12">
<h2>没有工地信息，<a href="/workyard" class="text-danger">创建工地</a></h2>
</div>
<?php endif;?>