<?php
$Entities = $this->Workyard()->getEntities();
?>
<div class="col-md-3 col-sm-3 col-xs-12 profile_left">
	<ul 
	id ="workyard_info"
	class="list-unstyled user_data"
	style="max-height: 430px; overflow: auto">
		<?php foreach ($Entities as $Entity):?>
    	<?php
            $name = $Entity->getName();
            $address = $Entity->getAddress();
            $address_path = $Entity->getAddress_path();
        ?>
    	<li data-address-path=<?=$address_path?>>
			<h4>
				<a href="javascript:;"><i class="fa fa-map-marker"></i>&nbsp;<strong><?=$name?></strong></a>
			</h4> <span class="text-muted"><?=$address?></span>
		</li>
    	<?php endforeach;?>
	</ul>
</div>

<div class="col-md-9 col-sm-9 col-xs-12">
	<div id="map_container" style="min-height: 600px; max-width: none;"></div>
</div>