<?php
$identity = $this->identity();
?>

<div class="page" data-name="WorkyardSuperAdminHomePage">
<?=$this->partial('admin/index/partial/super-admin/count.phtml')?>
<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>所有工地</h2>
					<ul class="nav navbar-right panel_toolbox"
						style="min-width: auto !important;">
						<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>

				<div class="x_content">
				<?=$this->partial('admin/index/partial/super-admin/all-workyard-info.phtml')?>
				</div>
			</div>
		</div>
	</div>
</div>
