<div class="button-sp-area">
	<a href="javascript:;" class="weui-btn weui-btn_plain-default">按钮</a> <a
		href="javascript:;"
		class="weui-btn weui-btn_plain-default weui-btn_plain-disabled">按钮</a>
	<a href="javascript:;" class="weui-btn weui-btn_plain-primary">按钮</a> <a
		href="javascript:;"
		class="weui-btn weui-btn_plain-primary weui-btn_plain-disabled">按钮</a>
	<a href="javascript:;" class="weui-btn weui-btn_mini weui-btn_primary">按钮</a>
	<a href="javascript:;" class="weui-btn weui-btn_mini weui-btn_default">按钮</a>
	<a href="javascript:;" class="weui-btn weui-btn_mini weui-btn_warn"
		id="myajax">按钮</a> <a href="javascript:;"
		class="weui-btn weui-btn_mini weui-btn_warn" id="myajax">按钮</a>
</div>
