<?php 
$searchContent = $this->searchContent;
?>
<div class="x_content search-container">
	<div class="well" style="overflow: none">
    <form 
    action=""
    method="get" 
    class="form-inline qin-search-form form-search-submit">
    	<div class="row">
    		<div class="col-md-12 col-sm-12 col-xs-12 ">
    			<?=$searchContent?>
    	</div>
    </div>
    <div class="ln_solid"></div>
    <h4>
    	<button type="submit" class="btn btn-default" >筛选</button>
    	<button type="reset" class="btn btn-link hidden" >重置</button>
    </h4>
    </form>
	</div>
</div>