<?php
$label = $this->label;
$name = $this->name;
$placeholder = $this->placeholder;
$value = $this->value;
$id = $this->id;

/* <?=$this->partial('partial/admin/form/textarea.phtml', [
    'id'    => '',
    'label' => '',
    'name' => '',
    'value' => '',
    'placeholder' => '',
	])?> */
?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"><?=$label?></label> 
	<div class="col-md-6 col-sm-6 col-xs-12">
    	<textarea 
    	class="form-control"
    	id ="<?=$id?>"
    	name="<?=$name?>"
    	placeholder="<?=$placeholder?>"><?=$value?></textarea>
	</div>
</div>