<?php 
$type  = $this->type;//string
$strongText = $this->strongText;//string
$normalText = $this->normalText;//string

$type = empty($type) ? 'success' : $type;
$classType = "alert-$type";

/* <?=$this->partial('partial/admin/pop/pop.phtml', [
 'type'         => '',//string
 'strongText'   => '',//string
 'normalText'   => '',//string
 ])?> */
?>

<div class="alert <?=$classType?> alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
    </button>
    <strong><?=$strongText?></strong><?=$normalText?>
</div>