<!DOCTYPE html>
<html lang="en">
  	<!-- include the head  -->
	<?=$this->partial('layout/admin/partial/head.phtml')?>

  <body class="nav-md">
  	
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col ">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/" class="site_title"><i class="fa fa-desktop"></i><span>工地巡逻管理后台</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <?=$this->partial('layout/admin/partial/profile.phtml')?>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <?=$this->partial('layout/admin/partial/navbar.phtml')?>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <?=$this->partial('layout/admin/partial/top-navigation.phtml')?>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main" style="min-height: 720px;">
        	<?=$this->content?>
        </div>
        <!-- /page content -->

        <!-- footer content -->
       <?=$this->partial('layout/admin/partial/footer.phtml')?>
        <!-- /footer content -->
      </div>
      
    </div>
 	<?=$this->partial('layout/admin/js/init.phtml')?>
  </body>
</html>
