<?php
use Api\Entity\UserEntity;
use Api\Service\UserManager;

$shiftID        = $this->shiftID;

$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);

$where = [
    UserEntity::FILED_WORKYARD_ID => $workyard_id,
    UserEntity::FILED_ROLE => UserManager::ROLE_WORKYARD_GUARD
];

$GuardEntities = $this->User()->getEntities($where);
$guards = [];

//选择当前所需的guard_ids
$getGuardIds = $shiftID ? $this->Shift()->getGuardIds($shiftID) : [];
    
foreach ($GuardEntities as $key=>$GuardEntity)
{
    $guard_id = $GuardEntity->getId();
    $username = $GuardEntity->getUsername();
    $selected = in_array($guard_id, $getGuardIds);
    $guard = [
        'id' => $guard_id,
        'text'=> $username,
        "selected" => $selected,
    ];
    $guards[] = $guard;
}
/* <?=$this->partial('partial/admin/form/select/user/select-multiple-guards.phtml', [
 'shiftID' => ''
 ])?> */

?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"
		for="first-name">人员安排：</label>
	<div class="col-md-6 col-sm-6 col-xs-12">
    	<select 
    	id ="guard_select"
    	name="guard_ids[]" 
    	class="form-control" 
    	data-json = <?=json_encode($guards)?>
    	multiple="multiple"
    	style="width:100%"
    	>
	</select>
	</div>
</div>
