<?php
$selectedId     = $this->selectedId;
$withDefualt    = $this->withDefualt;
$types = $this->User()->getAllRoles();

/* <?=$this->partial('partial/admin/form/select/user/select-roles.phtml', [
 'selectedId'  => null,
 'withDefualt' => true,
 ])?> */

?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"
		for="first-name">角色：</label>
	<div class="col-md-6 col-sm-6 col-xs-12">
    	<select name="role" class="form-control">
			<?php if ($withDefualt) :?>
		    	<option value="" >请选择...</option>
		    <?php endif;?>
			<?php if (count($types)) :?>
				<?php foreach ($types as $key=>$item) :?>
					<?php if ($selectedId === $key) :?>
					<option value=<?=$key?> selected="selected"><?=$item?></option>
					<?php else :?>
					<option value=<?=$key?>><?=$item?></option>
					<?php endif;?>
				<?php endforeach;?>
			<?php endif;?>
	</select>
	</div>
</div>
