<?php 
$title = $this->Website()->getTitle();
$record = $this->Website()->getRecord();
$identity = $this->identity();
$identity   = $this->identity();
$UserEntity = $this->User()->getEntity(null, $identity);
$userID     = $UserEntity->getId();
?>
<!DOCTYPE html>
<html lang="en">
	<?=$this->partial('layout/admin/partial/head.phtml')?>
  <body class="login">
    <div class="page" data-name="AuthChangePasswordPage">
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            	<h1><?=$title?></h1>
              	<h5>需重新设置密码</h5>
              <form 
              class="form-ajax-submit" 
              id="auth-change-password"
              action="<?='/api/user/changePassword/' . $userID . '?change_initial_password=true'?>" 
              method="post">
                  <div class="form-group">
                    <input type="password" class="form-control" placeholder="新密码"  name="password"/>
                  </div>
              
                  <div class="form-group">
                    <input type="password" class="form-control" placeholder="重新输入新密码" name="password_repeat"/>
                    <input type="hidden" name="tokenJson" value="<?=$this->tokenJson?>"/>
                  </div>
                  
                  <div>
                    <button type="submit" class="btn btn-default">确认提交</button>
                  </div>
              </form>
              <div class="clearfix"></div>

              <div class="separator">

                <div class="clearfix"></div>
                <br />

                <div>
                  <p><?=$record?></p>
                </div>
              </div>
          </section>
        </div>
      </div>
    </div>
 	<?=$this->partial('layout/admin/js/init.phtml')?>
  </body>
</html>
