<?php 
use Api\Service\UserManager;

$title = $this->Website()->getTitle();
$record = $this->Website()->getRecord();
$identity = $this->identity();
$UserEntity = $this->User()->getEntity(null, $identity);
$userID     = $UserEntity->getId();
$status = $UserEntity->getStatus();
$reason = '';
switch ($status)
{
    case UserManager::STATUS_WAIT_CHANGE_PASSWORD_NEW_CREATED:
        $reason = '新用户需要修改密码之后登陆';
        break;
    case UserManager::STATUS_WAIT_CHANGE_PASSWORD_RESET_PASSWORD:
        $reason = '您的密码已被管理员重置，请修改之后登陆';
        break;
}

$token = $this->Token()->getToken();
$action= "/api/user/changePassword/$userID?change_initial_password=true&token=$token";
?>
<!DOCTYPE html>
<html lang="en">
	<?=$this->partial('layout/admin/partial/head.phtml')?>
  <body class="login">
    <div class="page" data-name="AuthChangePasswordPage">
    
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            	<h1><?=$title?></h1>
              	<h5>需重新设置密码</h5>
              	<h5><?=$reason?></h5>
              <form 
              class="form-ajax-submit" 
              id="auth-change-password"
              action="<?=$action?>" 
              method="post"
              data-reason = "<?=$reason?>"
              >
                  <div class="form-group">
                    <input 
                    type="text" 
                    class="form-control" 
                    disabled="disabled" 
                    value="用户名:<?=$identity?>"/>
                  </div>
                  
                  <div class="form-group">
                    <input type="password" class="form-control" placeholder="新密码"  name="password"/>
                  </div>
              
                  <div class="form-group">
                    <input type="password" class="form-control" placeholder="重新输入新密码" name="password_repeat"/>
                    <input type="hidden" name="tokenJson" value="<?=$this->tokenJson?>"/>
                  </div>
                  
                  <div>
                    <button type="submit" class="btn btn-default">确认提交</button>
                  </div>
              </form>
              <div class="clearfix"></div>

              <div class="separator">
				<a href="/api/auth/logout">取消登录</a>
                <div class="clearfix"></div>
                <br />

                <div>
                  <p><?=$record?></p>
                </div>
              </div>
          </section>
        </div>
      </div>
    </div>
 	<?=$this->partial('layout/admin/js/init.phtml')?>
  </body>
</html>
