<?php 
$title = $this->Website()->getTitle();
$record = $this->Website()->getRecord();
?>
<!DOCTYPE html>
<html lang="en">
	<?=$this->partial('layout/admin/partial/head.phtml')?>
  <body class="login">
    <div class="page" data-name="LoginPage">
      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            	<h1><?=$title?></h1>
              	<h5>登录</h5>
              <form 
              class="form-ajax-submit" 
              id="form-login"
              action="/api/auth/login" 
              method="post">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="用户名"  name="username"/>
                  </div>
              
                  <div class="form-group">
                    <input type="password" class="form-control" placeholder="密码" name="password"/>
                    <input type="hidden" name="tokenJson" value="<?=$this->tokenJson?>"/>
                  </div>
                  
                  <div>
                    <button type="submit" class="btn btn-default">登&nbsp;录</button>
                  </div>
              </form>
              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">如忘记账户或密码，请联系管理员！
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <p><?=$record?></p>
                </div>
              </div>
          </section>
        </div>
      </div>
    </div>
 	<?=$this->partial('layout/admin/js/init.phtml')?>
  </body>
</html>
