<?php
use Api\Entity\PointEntity;

$shift_time_id  = $this->shift_time_id;
$workyard_id    = $this->workyard_id;
$shift_id       = $this->shift_id;

$PointEntities = $this->Point()->getEntitiesOnShift($workyard_id, $shift_id);

$all_point_count = count($PointEntities);
$all_done_point_count = $this->ShiftTimePoint()->getCountOnDone($shift_time_id);
?>

<div 
style="margin-top: 0px; 
margin-bottom:60px"
id="my-point-on-working"
data-all-count="<?=$all_point_count?>"
data-done-count="<?=$all_done_point_count?>"
>
    <div class="weui-cells__title">共<?=$all_point_count?>个巡检点，已巡检<?=$all_done_point_count?>个 </div>
    <div class="weui-cells" style="margin-top: 0px">
        <?php foreach ($PointEntities as $PointEntity) :?>
        <?php
        $point_id  = $PointEntity->getId();
        $pointName = $PointEntity->getName();
        $address   = $PointEntity->getAddress();
        
        //该巡检点巡检信息
        $ShiftTimePointEntity = $this->ShiftTimePoint()->getEntity($shift_time_id, $point_id);
        $has_done = !empty($ShiftTimePointEntity->getId());
        $time = $ShiftTimePointEntity->getTime();
        $note = $ShiftTimePointEntity->getNote();
        
        $time = $time ? date('Y-m-d H-i-s', $time) : null;
        ?>
          <a 
          class="weui-cell weui-cell_access alert-point-info" 
          href="javascript:;"
          data-point-point-id="<?=$this->escapehtml($point_id)?>"
          data-point-shift-time-id="<?=$this->escapehtml($shift_time_id)?>"
          data-point-address="<?=$this->escapehtml($address)?>"
          data-point-time="<?=$this->escapehtml($time)?>"
          data-point-note="<?=$this->escapehtml($note)?>"
          >
            <div class="weui-cell__bd">
              <p><?=$pointName?></p>
            </div>
            <div class="weui-cell__ft">
            <?php if($has_done):?>
            <i class="weui-icon-success-no-circle"></i>
            <?php else :?>
           	 待巡检
            <?php endif;?>
            </div>
          </a>
        
        <?php endforeach;?>
    </div>
</div>
