<?php 
$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$UserEntity  = $this->User()->getEntityByIdentity($identity);
$userID = $UserEntity->getId();

// 当前巡检任务
$ShiftEntity = $this->Shift()->getGuardShift($userID, $workyard_id);

?>

<!-- 顶部导航 -->
<?php $this->placeholder('narbar')->captureStart();?>
<?=$this->partial('layout/weixin/partial/narbar-workyard.phtml')?>
<?php $this->placeholder('narbar')->captureEnd();?>

<?php $this->placeholder('content')->captureStart();?>
<!-- 工地信息 -->
<?=$this->partial('guard/index/partial/workyard.phtml', [
    'workyard_id' => $workyard_id
])?>

<?php if(!empty($ShiftEntity)) :?>
<!-- 值班安排 -->
<?=$this->partial('guard/index/partial/on-working-shift.phtml', [
    'ShiftEntity' => $ShiftEntity,
    'userID' => $userID,
    'workyard_id' => $workyard_id,
])?>
<br/>
<?php else :?>
<!-- 显示排班情况 -->
<div class="weui-panel__bd">
	<div class="weui-media-box weui-media-box_text">
		<h4 class="weui-media-box__title">今日无值班安排！</h4>
	</div>
</div>
<?php endif;?>








<!-- 显示所有巡检点popup -->
<?=$this->partial('guard/index/partial/all-points.phtml', [
    'workyard_id' => $workyard_id
])?>

<?=$this->partial('partial/weixin/popup/popup.phtml', [
    'id' => 'log-shift-popup'
])?>

<?php $this->placeholder('content')->captureEnd();?>

<?=$this->partial('partial/weixin/page/basic-page.phtml', [
    'pageName'    => 'GuardIndexPage',
    'pageTitle'   => '巡检任务',
    'narbar'      => '',//指定导航条的url
    'narbar'     => $this->placeholder('narbar'),
    'content'     => $this->placeholder('content'),
])?>