<?php 
$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$WorkyardEntity = $this->Workyard()->getWorkyardEntity($workyard_id);
$workyard_name = $WorkyardEntity->getName();
$address = $WorkyardEntity->getAddress();
$desc = $WorkyardEntity->getNote();
?>

<?php $this->placeholder('narbar')->captureStart();?>
<?=$this->partial('layout/weixin/partial/narbar-workyard.phtml')?>
<?php $this->placeholder('narbar')->captureEnd();?>

<?php $this->placeholder('content')->captureStart();?>
<?=$this->partial('layout/weixin/partial/workyard.phtml')?>
<?=$this->partial('guard/index/partial/shifts.phtml')?>
<?php $this->placeholder('content')->captureEnd();?>

<?=$this->partial('partial/weixin/page/basic-page.phtml', [
    'pageName'    => 'GuardWordPage',
    'pageTitle'   => '巡检任务',
    'narbar'      => '',//指定导航条的url
    'narbar'     => $this->placeholder('narbar'),
    'content'     => $this->placeholder('content'),
])?>