<?php 
$identity    = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
$UserEntity  = $this->User()->getEntityByIdentity($identity);
$user_id     = $UserEntity->getId();

//check has shift on working 
$has_shifts_on_working= $this->ShiftGuard()->hasShiftsOnWorking($user_id, $workyard_id);
//获取某一巡逻员是否有值班安排
$has_shifts_on_plan   = $this->ShiftGuard()->hasShiftsOnPlan($user_id, $workyard_id);

//test
// $has_shifts_on_working = false;
// $has_shifts_on_plan    = false;
?>

<?php $this->placeholder('content')->captureStart();?>

<!-- 工地信息 -->
<?=$this->partial('guard/index/partial/workyard.phtml', [
    'workyard_id' => $workyard_id
])?>

<!-- 如果有值班任务 -->
<?php if($has_shifts_on_working) :?>

<!-- 值班安排 -->
<?=$this->partial('guard/index/partial/on-working/shift.phtml', [
    'user_id'       => $user_id,
    'workyard_id'   => $workyard_id,
])?>

<br/>

<!-- 如果没有当前值班任务，但是有值班安排 -->
<?php elseif ($has_shifts_on_plan):?>
<?=$this->partial('partial/weixin/empty/weui-msg.phtml', [
    'title' => '无进行中的巡逻任务',
    'desc' => '请留意值班安排',
])?>
<!-- 显示1条值班安排 -->
<?=$this->partial('guard/index/partial/on-plan/shift.phtml', [
    'user_id'       => $user_id,
    'workyard_id'   => $workyard_id,
])?>
<br>
<!-- 无值班任务和安排 -->
<?php else :?>

<?=$this->partial('partial/weixin/empty/weui-msg.phtml', [
    'title' => '无内容',
])?>
<?php endif;?>

<?php $this->placeholder('content')->captureEnd();?>

<?=$this->partial('partial/weixin/page/basic-page.phtml', [
    'pageName'    => 'GuardIndexPage',
    'pageTitle'   => '巡逻任务',
    'narbar'      => '',//指定导航条的url
//     'narbar'     => $this->placeholder('narbar'),
    'content'     => $this->placeholder('content'),
])?>
