<?php 
use Zend\Paginator\Paginator;

$paginator  = $this->paginator;
$route      = $this->route;
$action     = $this->action;
$search     = $this->search;
?>
<?php if (count($paginator) && $paginator instanceof Paginator) :?>
	<div class="ln_solid"></div>
	<?= $this->paginationControl(
	    $paginator,
        'Sliding',
        'partial/paginator/my_pagination_control.phtml',
	    ['search' => $search, 'route'=> $route, 'action'=>$action]
    ) ?>
<?php endif;?>