<?php
$label = $this->label;
$value = $this->value;
$id   = $this->id;

/* <?=$this->partial('partial/admin/form/input/input-static.phtml', [
    'label' => '',
    'value' => '',
	])?> */
?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"><?=$label?></label>
	<p class="form-control-static" id = "<?=$id?>">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$value?></p>
</div>
