<?php
$shiftID        = $this->shiftID;

$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);

$select2_config = $this->Guard()->getGuardDataForSelect2AsJson($workyard_id, $shiftID)
    
/* <?=$this->partial('partial/admin/form/select/guard/select-multiple-guards.phtml', [
 'shiftID' => ''
 ])?> */

?>

<div class="form-group">
	<label class="control-label col-md-3 col-sm-3 col-xs-12"
		for="first-name">巡检员：</label>
	<div class="col-md-6 col-sm-6 col-xs-12">
    	<select 
    	id ="guard_select"
    	name="guard_ids[]" 
    	class="form-control" 
    	multiple="multiple"
    	style="width:100%"
    	data-json = <?=$select2_config?>
    	>
		</select>
		<?php if (empty($select2_config)) :?>
    	<a href="/guard">
        <i class="glyphicon glyphicon-plus"></i>请先增加巡检员</a>
        <?php endif;?>
	</div>
</div>
