<?php
use Api\Entity\PointEntity;

$workyard_id = $this->workyard_id;
$where[PointEntity::FILED_WORKYARD_ID] = $workyard_id;
$Entities = $this->Point()->getEntities($where);
$count = count($Entities);
?>
    <h5 class="text-muted">共<?=$count?>个巡检点</h5>
    <ul class="list-unstyled user_data" style="max-height: 530px; overflow: auto">
    	<?php if($count):?>
        	<?php foreach ($Entities as $Entity):?>
        	<?php 
        	$pointName = $Entity->getName();
        	$address   = $Entity->getAddress();
        	?>
        	<li>
    		<div class="list-group-item">
            	<h4 class="list-group-item-heading"><?=$pointName?></h4>
            	<p class="list-group-item-text"><?=$address?></p>
          	</div>
		</li>
        	<?php endforeach;?>
    	<?php else :?>
    	<li>
    		<p>暂无巡检点， <a href="/point" class="text-danger">新增巡检点</a></p>
    	</li>
    	<?php endif;?>
    </ul>
