<?php
use Api\Entity\PointEntity;

$workyard_id = $this->workyard_id;
$where[PointEntity::FILED_WORKYARD_ID] = $workyard_id;
$Entities = $this->Point()->getEntities($where);
?>
    <h4><a href="/point">巡检点</a></h4>
    <ul class="list-unstyled user_data" style="max-height: 430px; overflow: auto">
    	<?php foreach ($Entities as $Entity):?>
    	<?php 
    	$pointName = $Entity->getName();
    	$address   = $Entity->getAddress();
    	?>
    	<li>
    		<p><i class="fa fa-map-marker"></i>&nbsp;<strong><?=$pointName?></strong></p>
    		<small class="text-muted"><?=$address?></small>
    	</li>
    	<?php endforeach;?>
    </ul>
