<div class="weui-msg">
	<div class="weui-msg__icon-area">
		<i class="weui-icon-waiting weui-icon_msg"></i>
	</div>
	<div class="weui-msg__text-area my_test_left">
		<h2 class="weui-msg__title">未查询到，可能：</h2>
		<p class="weui-msg__desc">1.您未购买返现产品；</p>
		<p class="weui-msg__desc">2.已购买返现产品，需在下单7天或确认收货之后，方可查询到返现信息；</p>
		<p class="weui-msg__desc">3.您的返现金额已领取完成；</p>
		<p class="weui-msg__desc">
			4.<a href="https://h5.youzan.com/v2/showcase/feature?alias=wxerx4ac&winzoom=1&reft=1512116719817&spm=g319947441">更多返现规则</a>
		</p>
	</div>
	<div class="weui-msg__opr-area">
		<p class="weui-btn-area">
			<a href="https://h5.youzan.com/v2/goods/3eo35r8ldw7hs"
				class="weui-btn weui-btn_primary">立即参加</a>
		</p>
	</div>
</div>