<!-- 积分返现模块顶部导航菜单 -->
<div class="weui-form-preview">
	<div class="weui-form-preview__ft" id="my_menu">
		<a class="weui-form-preview__btn weui-form-preview__btn_default"
			href="/point">领取积分</a> 
		<a class="weui-form-preview__btn weui-form-preview__btn_default"
			href="/commission">分销员奖金</a>
		<a class="weui-form-preview__btn weui-form-preview__btn_default"
			href="/withdraw">申请提现</a>
	</div>
</div>
<!-- /积分返现模块顶部导航菜单 -->