<?php 
$id = $this->id;
$token = $this->Token()->getToken();
$Register = $this->Register()->getEntityById($id);
$workyard_name= $Register->getWorkyard_name();
$workyard_address     = $Register->getWorkayrd_address();
$admin_realname       = $Register->getAdmin_realname();
$admin_tel       = $Register->getAdmin_tel();
$created_at = $Register->getCreated_at();
?>
<?php $this->placeholder('formContent')->captureStart();?>
	<?=$this->partial('partial/admin/form/input/input-static.phtml', [
        'label'  => 'id：',
	    'value'  => $id,
	])?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '工地名称：',
	    'name' => 'name',
	    'placeholder' => '请输入工地名称',
	    'type' => 'text',
	    'value'=>$workyard_name,
	])?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '工地地址：',
	    'name' => 'address',
	    'placeholder' => '请输入工地地址',
	    'type' => 'text',
	    'value'=>$workyard_address,
	])?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '管理员-用户名：',
	    'name' => 'username',
	    'value'=> '',
	    'placeholder' => '请输入用户名',
	    'type' => 'text'
	])?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '真实姓名：',
	    'name' => 'realname',
	    'value'=> $admin_realname,
	    'placeholder' => '请输入真实姓名',
	    'type' => 'text'
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '手机号：',
	    'name' => 'tel',
	    'value'=> $admin_tel,
	    'placeholder' => '请输入手机号',
	    'type' => 'text'
	])?>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?php $this->placeholder('formContent')->captureEnd() ?>
<?=$this->partial('partial/admin/page/modal/form-modal.phtml', [
    'pageName'      => 'RegisterSuccessPage',
    'pageTitle'     => '注册成功',
    'modalSize'     => 'lg',
    'form_id'       => 'form-register-success',
    'action'        => "/api/register/success/$id?token=$token",
    'formContent'   => $this->placeholder('formContent'),
])?> 
