<?php $this->headTitle('消费积分');?>
<div class="page__hd">
	<div class="weui-flex js_category">
        <p class="weui-flex__item">提现记录</p>
    </div>
</div>
<div class="page__bd">
	<?php if (count($this->paginator)){?>
    	<div class="mypaginator" id="mypaginator">
    		<!-- paginator list -->
            	<?=$this->partial('application/record-withdraw/paginator.phtml', ['paginator' => $this->paginator])?>
            	<!-- /paginator list -->
    	</div>
    	
    <?php }else {?>
    	<?=$this->partial('application/partial/defualt/empty.phtml')?>
    <?php }?>
</div>
<div class="myhidden config">
	<input type="hidden" name="menu" value="提现记录">
</div>
<!-- load more -->
<?=$this->partial('partial/admin/load/loadmore.phtml')?>
<!-- /load more -->

<script type="text/javascript" src="/js/service/Paginator.js"></script>
<script type="text/javascript" src="/js/manager/withdraw_history.js"></script>
