<!-- paginator -->
<?php foreach ($this->paginator as $item){?>
<div class="weui-form-preview">
	<div class="weui-form-preview__hd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">提现状态</label> <em
				class="weui-form-preview__value status">
				<?php 
				switch ($item['status'])
				{
				    case \Application\Service\WithdrawManager::WITHDRAW_STATUS_SUCCESSED:
				        echo "<i class='weui-icon-success-no-circle'></i>提现成功";
				        break;
				    case \Application\Service\WithdrawManager::WITHDRAW_STATUS_WAIT_REMIT: 
				        echo "<i class='weui-icon-info-circle'></i>待打款";
				        break;
				    case \Application\Service\WithdrawManager::WITHDRAW_STATUS_FAILED:
			        default:
			            echo "<i class='weui-icon-warn'></i>提现失败";
				}
				?>
				</em>
		</div>
	</div>
	<div class="weui-form-preview__bd">
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">提现编号</label> <span
				class="weui-form-preview__value"><?=$item['withdraw_id']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">提现总金额</label> <span
				class="weui-form-preview__value"><?=$item['cashback_total']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">手续费</label> <span
				class="weui-form-preview__value"><?=$item['cashback_fee']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">实际提现</label> <span
				class="weui-form-preview__value"><?=$item['cashback_real']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">银行卡号</label> <span
				class="weui-form-preview__value"><?=$item['card_no']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">所属银行</label> <span
				class="weui-form-preview__value"><?=$item['card_bank_name']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">银行地区</label> <span
				class="weui-form-preview__value"><?=$item['card_bank_area']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">开户支行</label> <span
				class="weui-form-preview__value"><?=$item['card_bank_branch_name']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">银行卡持有人</label> <span
				class="weui-form-preview__value"><?=$item['card_user_name']?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">申请日期</label> <span
				class="weui-form-preview__value"><?=date('Y-m-d H:i:s', $item['created'])?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">打款日期</label> <span
				class="weui-form-preview__value"><?=empty($item['remit_time']) ? '-' : date('Y-m-d', $item['remit_time'])?></span>
		</div>
		<div class="weui-form-preview__item">
			<label class="weui-form-preview__label">备注</label> <span
				class="weui-form-preview__value"><?=$item['remit_note']?></span>
		</div>
	</div>
</div>
<br />
<?php }?>
<!-- 分页导航-->
<?= $this->paginationControl($this->paginator);?>
<!-- /分页导航 -->
<!-- /paginator -->
