<?php if ($this->isFree){?>
<!-- for free -->
<div class="js_dialog" id="iosDialog1" style="display: none;">
	<div class="weui-mask"></div>
	<div class="weui-dialog">
		<div class="weui-dialog__hd">
			<strong class="weui-dialog__title">免费申请分销员</strong>
		</div>
		<div class="weui-dialog__bd" style="text-align: left">
			<p><?=date('Y-m-d', $this->config['pay']['free_of_charge']['end_time'])?>日(含)之前可免费申请为坦罕斯商城分销员！</p>
		</div>
		<div class="weui-dialog__ft">
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_default" id="dialog_close">关闭</a>
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_primary"
				id="dialog_confirm">免费申请</a>
		</div>
	</div>
</div>
<!-- /for free -->
<?php }else {?>
<!-- needed pay -->
<div class="js_dialog" id="iosDialog1" style="display: none;">
	<div class="weui-mask"></div>
	<div class="weui-dialog">
		<div class="weui-dialog__hd">
			<strong class="weui-dialog__title">分销员缴费</strong>
		</div>
		<div class="weui-dialog__bd" style="text-align: left">
			<p>成为分销员需缴费<?=$this->config['pay']['payment']?>元；</p>
			<p>同时赠送<?=$this->config['point']['nums']?>元等值消费积分;</p>
			<p>消费积分可在积分商城兑换商品！</p>
		</div>
		<div class="weui-dialog__ft">
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_default" id="dialog_close">关闭</a>
			<a href="/seller/pay"
				class="weui-dialog__btn weui-dialog__btn_primary"
				id="">缴费</a>
		</div>
	</div>
</div>
<!-- /needed pay -->
<?php }?>
