<?php $this->headTitle('招募分销员');?>
<link rel="stylesheet"
	href="/vendor/youzan/base_e2a094b7897f0b4e14424f3adb0b8c4b.css">
<link rel="stylesheet"
	href="/vendor/youzan/salesman_7d06b73f8f76d179d150543b24b42908.css">
<link rel="stylesheet"
	href="/vendor/youzan/direct_seller_f61d483c143a5928df0160a80f06d675.css">
<div class="container " style="min-height: 771px;">
	<div class="content-body">
		<div class="custom-richtext">
			<table>
				<tbody>
					<tr>
						<td style="word-break: break-all;" width="358" valign="top">
							<p style="line-height: 1.75em;">小伙伴，欢迎加入我们！</p>
							<p style="line-height: 1.75em;">我们是坦罕斯商城运营团队，竭诚为你的销售工作提供完善的支持。我们诚挚邀请你加入我们的销售推广计划，一起分享收获的喜悦。你只需将高品质商品分享推荐给他人，收获他人的感谢的同时，挣得属于自己的利润。</p>
						</td>
					</tr>
				</tbody>
			</table>
			<table>
				<tbody>
					<tr>
						<td
							style="word-break: break-all; background-color: rgb(85, 168, 212);"
							width="351" valign="top"><span style="color: rgb(255, 255, 255);">1.
								推广说明</span></td>
					</tr>
					<tr>
						<td style="word-break: break-all;" width="351" valign="top">
							<ol style="list-style-type: decimal;">
								<li>
									<p style="line-height: 1.75em;">首先需申请成为本商城分销员；</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">成为分销员之后将参加推广的商品链接发送到朋友圈/微信好友等社交平台；</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">买家点击链接并下单成功，则此订单算作分销员的业绩；</p>
								</li>
							</ol>
						</td>
					</tr>
					<tr>
						<td colspan="1" rowspan="1" style="word-break: break-all;"
							width="351" valign="top">
							<p style="line-height: 1.75em;">其他：</p>
							<ol style="list-style-type: decimal;">
								<li>
									<p style="line-height: 1.75em;">订单交易完成前发生退款的订单，相应的分销员业绩将扣除相应的退款金额；</p>
								</li>
								<li>
									<p>
										<span style="line-height: 1.75em;">仅在线支付的订单算作业绩，不包括货到付款订单。</span>
									</p>
									<p>
										<span style="line-height: 1.75em;"></span>
									</p>
								</li>
							</ol>
						</td>
					</tr>
				</tbody>
			</table>
			<table width="362">
				<tbody>
					<tr>
						<td
							style="word-break: break-all; background-color: rgb(85, 168, 212);"
							width="351" valign="top">
							<p>
								<span style="color: rgb(255, 255, 255);">2. 奖金说明</span>
							</p>
						</td>
					</tr>
					<tr>
						<td style="word-break: break-all;" width="351" valign="top">
							<p>1、分销员奖金包含2部分：订单立返奖金 + 月度统计奖金：</p>
							<p>
								<strong>订单立返奖金</strong>：<br>
							</p>
							<p>1、分销员每推广一笔订单，即可获取订单金额的3%；</p>
							<p>
								2、在订单交易完成之后可提现立返奖金至微信红包；<br>
							</p>
							<p>
								<br>
							</p>
						</td>
					</tr>
				</tbody>
			</table>
			<table width="362">
				<tbody>
					<tr>
						<td
							style="word-break: break-all; background-color: rgb(85, 168, 212);"
							width="351" valign="top">
							<p>
								<span style="color: rgb(255, 255, 255);">3. 月度累计奖金</span>
							</p>
						</td>
					</tr>
					<tr>
						<td style="word-break: break-all;" width="351" valign="top">
							<ol style="list-style-type: decimal;">
								<li>
									<p style="line-height: 1.75em;">
										推广订单金额在<span style="color: rgb(255, 0, 0);">1万~49.9999万元</span>之间的，获得<span
											style="color: rgb(255, 0, 0);">3%</span>的业绩提成；
									</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">
										推广订单金额在<span style="color: rgb(255, 0, 0);">50万元～99.999万元</span>之间的，获得<span
											style="color: rgb(255, 0, 0);">5%</span>的业绩提成；
									</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">
										推广订单金额在<span style="color: rgb(255, 0, 0);">100万元～999.999万元<span
											style="color: rgb(0, 0, 0);">之</span></span>间的，获得<span
											style="color: rgb(255, 0, 0);">7%</span>的业绩提成；
									</p>
								</li>
							</ol>
						</td>
					</tr>
					<tr>
						<td colspan="1" rowspan="1" valign="top">
							<ol style="list-style-type: decimal;">
								<li>
									<p style="line-height: 1.75em;">月度推广订单金额为分销员历史业绩累计，永不清零；</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">
										每月1号统计、<span style="line-height: 28px;">核算</span>分销员上个自然月的业绩；
									</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">
										核算方式采用极差计算：应发奖金=当前业绩提成总额-历史已发奖金总额；<br>
									</p>
								</li>
								<li>
									<p>
										<span style="line-height: 1.75em;"><span
											style="line-height: 28px;">每月10号，我们会将月度业绩奖励</span>通过财务打款方式打入各分销员提供的银行账号。</span>
									</p>
								</li>
							</ol>
						</td>
					</tr>
				</tbody>
			</table>
			<table>
				<tbody>
					<tr>
						<td
							style="word-break: break-all; background-color: rgb(85, 168, 212);"
							width="359" valign="top">
							<p>
								<span style="color: rgb(255, 255, 255);">4. 其他说明</span>
							</p>
						</td>
					</tr>
					<tr>
						<td style="word-break: break-all;" width="359" valign="top">
							<ol style="list-style-type: decimal;">
								<li>
									<p style="line-height: 1.75em;">分享前，请确定商品页面有【···】按钮；</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">销售过程中有任何疑问，请直接在微信公众号内询问或直接致电；</p>
								</li>
								<li>
									<p style="line-height: 1.75em;">已售出商品的任何售后问题，由本商城处理；</p>
								</li>
								<li>
									<p>
										<span style="line-height: 1.75em;">不传播或者扩散有关于政治、色情等任何违法的信息，一经发现，直接踢你出局，如果触犯任何法律相关问题，商城不负任何责任；</span>
									</p>
								</li>
							</ol>
						</td>
					</tr>
				</tbody>
			</table>
			<table>
				<tbody>
					<tr>
						<td
							style="word-break: break-all; background-color: rgb(85, 168, 212);"
							width="359" valign="top">
							<p style="margin-top: 0px;">
								<span style="color: rgb(255, 255, 255);">5. 联系方式</span>
							</p>
						</td>
					</tr>
					<tr>
						<td style="word-break: break-all;" width="359" valign="top">
							<p style="margin-top: 0px; line-height: 1.75em;">
								<span style="line-height: 1.75em;">客服人员：</span><br>
							</p>
							<ul style="list-style-type: disc;">
								<li>
									<p
										style="margin-top: 0px; margin-bottom: 0px; padding: 0px; white-space: normal; line-height: 2em;">（扎鲁特旗）乌兰图雅：188-4757-9992</p>
								</li>
								<li>
									<p
										style="margin-top: 0px; margin-bottom: 0px; padding: 0px; white-space: normal; line-height: 2em;">（北京）秦崇：153-1371-5521</p>
								</li>
							</ul>
							<p style="margin-top: 0px; line-height: 1.75em;">邮箱：huhekeji@qq.com</p>
							<p style="margin-top: 0px; line-height: 1.75em;">无论是销售、对账，还是结算问题，请通过以上方式咨询。</p>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="js-bottom-opts js-footer-auto-ele bottom-fix">
		<?php if ($this->isSeller){?>
		<div class="btn-sp">
			<a
				href="/commission" class="btn btn-white"> <i class="btn-icon btn-icon-center"></i> <span>已成为分销员->分销员中心</span>
			</a>
		</div>
		<?php }else {?>
		<div class="btn-1-1">
			<span class="btn btn-green font-size-14 js-apply-salesman"
				id="btn_saler"><?=$this->isFree ? '免费申请' : '申请分销员'?></span>
		</div>
    	<?php }?>
	</div>
</div>
<?=$this->partial('application/seller/confirm.phtml', 
    [
        'config'=>$this->config,
        'isFree'=>$this->isFree,
    ])?>
<!-- toast-->
<?=$this->partial('application/partial/feedback/toast.phtml')?>
<!-- /toast-->
<script type="text/javascript" src="/js/service/Toast.js"></script>    
<script type="text/javascript" src="/js/manager/seller.js"></script>
<script type="text/javascript" src="/js/weixin/wx.config.js"></script>  

