<?php
use Api\Service\UserManager;

$title = $this->Website()->getTitle();
$record = $this->Website()->getRecord();

$identity = $this->identity();
$UserEntity = $this->User()->getEntity(null, $identity);
$userID     = $UserEntity->getId();
$status = $UserEntity->getStatus();
$reason = '';
switch ($status)
{
    case UserManager::STATUS_WAIT_CHANGE_PASSWORD_NEW_CREATED:
        $reason = '新用户需要修改密码之后登陆';
        break;
    case UserManager::STATUS_WAIT_CHANGE_PASSWORD_RESET_PASSWORD:
        $reason = '您的密码已被管理员重置，请修改之后登陆';
        break;
}
?>
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <?=$this->headTitle("设置密码-$title") ?>

    <?=$this->partial('layout/weixin/css/css.phtml')?>
</head>
<body ontouchstart="">
	<div class="container"> 
		<div class="page" data-name="AuthChangePasswordPage">
    	<header class='demos-header'>
    		<h2 class="demos-title">修改密码</h2>
    		<h4 class="weui-msg__title"><?=$reason?></h4>
    	</header>
    	<form 
    	action="<?='/api/user/changePassword/' . $userID . '?change_initial_password=true'?>" 
    	class="form-ajax-submit" 
    	id="auth-change-password"
    	method="post"
    	data-reason = "<?=$reason?>"
    	>
        	<div class="weui-cells ">
        		 <div class="weui-cell">
                    <div class="weui-cell__bd">
                      <p>用户名</p>
                    </div>
                    <div class="weui-cell__ft"><?=$identity?></div>
                </div>
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'password',
                    'placeholder'=>'新密码',
                    'type'=>'password',
                  ]);?>
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'password_repeat',
                    'placeholder'=>'重新输入新密码',
                    'type'=>'password',
                  ]);?>
        	</div>
        	<?=$this->partial('partial/weixin/button/submit.phtml', [
                'title' => '确认提交',
            ])?>
    	</form>
    
    	<div class="weui-footer weui-footer_fixed-bottom">
    		<p class="weui-footer__text"><?=$record?></p>
    	</div>
    	</div>
	</div>
	<?=$this->partial('layout/weixin/js/init.phtml')?>
</body>
</html>