<?php
$title = $this->Website()->getTitle();
$record = $this->Website()->getRecord();

$identity = $this->identity();
$UserEntity = $this->User()->getEntity(null, $identity);
$userID     = $UserEntity->getId();
?>
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <?=$this->headTitle("设置密码-$title") ?>

    <?=$this->partial('layout/weixin/css/css.phtml')?>
</head>
<body ontouchstart="">
	<div class="container"> 
		<div class="page" data-name="LoginPage">
    	<header class='demos-header'>
    		<h2 class="demos-title">重置密码</h2>
    	</header>
    	<form 
    	action="<?='/api/user/changePassword/' . $userID . '?change_initial_password=true'?>" 
    	class="form-ajax-submit" 
    	id="form-login"
    	method="post"
    	>
        	<div class="weui-cells ">
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'password',
                    'placeholder'=>'新密码',
                    'type'=>'password',
                  ]);?>
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'password',
                    'placeholder'=>'重新输入新密码',
                    'type'=>'password_repeat',
                  ]);?>
        	</div>
        	<?=$this->partial('partial/weixin/button/submit.phtml', [
                'title' => '确认提交',
            ])?>
    	</form>
    
    	<div class="weui-footer weui-footer_fixed-bottom">
    		<p class="weui-footer__text"><?=$record?></p>
    	</div>
    	</div>
	</div>
	<?=$this->partial('layout/weixin/js/init.phtml')?>
</body>
</html>