<?php
$title = $this->Website()->getTitle();
$token = $this->Token()->getToken();

?>
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport"
	content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
    <?=$this->headTitle("登录-$title") ?>

    <?=$this->partial('layout/weixin/css/css.phtml')?>
</head>
<body ontouchstart="">
	<div class="container"> 
		<div class="page" data-name="LoginPage">
    	<header class='demos-header'>
    		<h2 class="demos-title">巡检员登录</h2>
    	</header>
    	<form 
    	action="/api/auth/login?token=<?=$token?>" 
    	class="form-ajax-submit" 
    	id="form-login"
    	method="post"
    	>
        	<div class="weui-cells ">
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'username',
                    'placeholder'=>'请输入用户名',
                  ]);?>
                  
        		<?=$this->partial('partial/weixin/form/input/input.phtml', [
                    'name'=>'password',
                    'placeholder'=>'请输入登录密码',
                    'type'=>'password',
                  ]);?>
        	</div>
        	<?=$this->partial('partial/weixin/button/submit.phtml', [
                'title' => '登录',
            ])?>
    	</form>
    	<?=$this->partial('layout/weixin/partial/footer.phtml')?>
    	
    	</div>
	</div>
	<?=$this->partial('layout/weixin/js/init.phtml')?>
</body>
</html>
