<?php
// 当前巡逻任务
$workyard_id = $this->workyard_id;
$user_id = $this->user_id;

//about shift
$ShiftEntity    = $this->ShiftGuard()->getNextShiftOnPlan($workyard_id, $user_id);

?>
<!-- 标题 -->
<div class="weui-cells">
  <div class="weui-cell">
    <div class="weui-cell__hd"><i class="fa  fa-coffee icon-in-list"></i></div>
    <div class="weui-cell__bd">
      <p>值班安排：</p>
    </div>
    <div class="weui-cell__ft"></div>
  </div>
</div>

<!-- 值班内容 -->
<?=$this->partial('partial/weixin/preview/sfhit-plan.phtml', [
    'ShiftEntity' =>$ShiftEntity
])?>

<!-- 显示所有巡逻点popup -->
<?=$this->partial('partial/weixin/popup/points.phtml', [
    'workyard_id' => $workyard_id,
//     'shift_id' => $shift_id,
])?>
