<div class="js_dialog" id="iosDialog1" style="display: none;">
	<div class="weui-mask"></div>
	<div class="weui-dialog">
		<div class="weui-dialog__hd">
			<strong class="weui-dialog__title">银行卡确认</strong>
		</div>
		<div class="weui-form-preview__bd">
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">银行卡号：</label>
                    <span class="card_no"></span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">发卡银行：</label>
                    <span class="card_bank_name"></span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">卡片类型：</label>
                    <span class="card_type_name"></span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">持卡人姓名：</label>
                    <span class="card_user_name"></span>
                </div>
                <div class="weui-form-preview__item">
                    <label class="weui-form-preview__label">手机号：</label>
                    <span class="card_user_tel"></span>
                </div>
            </div>
		<div class="weui-dialog__ft">
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_default dialog_close" id="">返回修改</a>
			<a href="javascript:;"
				class="weui-dialog__btn weui-dialog__btn_primary"
				id="dialog_confirm">确认提交</a>
		</div>
	</div>
</div>
