<?php $this->headTitle('设置银行卡');?>
<div class="page__bd">
	<form action="/card/editSecond" method="post" id="form_card">
		<div class="weui-cells weui-cells_form">
			<div class="weui-cell">
				<div class="weui-cell__hd">
					<label for="" class="weui-label">银行卡号</label>
				</div>
				<div class="weui-cell__bd">
					<input class="weui-input" 
					 pattern="[0-9]*" placeholder="请输入您的银行卡号"
					 value="<?=$this->escapehtml($this->card['card_no'])?>" type="text" name="card_no">
					 <input type="hidden" 
					 value="<?=$this->escapehtml($this->card['card_no'])?>" 
					 name="card_no_old">
				</div>
				<div class="weui-cell__ft">
					<i class="weui-icon-warn"></i>
				</div>
			</div>
			<div class="weui-cell">
				<div class="weui-cell__hd">
					<label for="" class="weui-label">持卡人姓名</label>
				</div>
				<div class="weui-cell__bd">
					<input class="weui-input" placeholder="请输入持卡人真实姓名"
						value="<?=$this->escapehtml($this->card['card_user_name'])?>" type="text"
						name="card_user_name">
				</div>
				<div class="weui-cell__ft">
					<i class="weui-icon-warn"></i>
				</div>
			</div>
			<div class="weui-cell">
				<div class="weui-cell__hd">
					<label for="" class="weui-label">手机号</label>
				</div>
				<div class="weui-cell__bd">
					<input class="weui-input" pattern="[0-9]*" placeholder="请输入您手机号"
						value="<?=$this->escapehtml($this->card['card_user_tel'])?>" type="number"
						name="card_user_tel">
				</div>
				<div class="weui-cell__ft">
					<i class="weui-icon-warn"></i>
				</div>
			</div>
		</div>
		<!-- token -->
		<input type="hidden" value="<?=$this->token?>" name="token">
		<!-- /token -->
		<!-- id -->
		<input type="hidden" value="<?=$this->card['id'] ?>" name="id">
		<!-- /id -->
	</form>
	<div class="weui-btn-area">
		<a class="weui-btn weui-btn_primary" href="javascript:;"
			id="form_next_page">下一步</a>
		<a class="weui-btn weui-btn_default" href="javascript:history.back();"
			id="">返回</a>
	</div>
	<!-- 银行卡说明 -->
	<div class="weui-media-box weui-media-box_text">
		<p class="weui-media-box__desc">不支持绑定信用卡！</p>
	</div>
	<!-- /银行卡说明 -->
</div>
<!-- toast-->
<?=$this->partial('partial/admin/feedback/toast.phtml')?>
<!-- /toast-->
<!-- dialog2 -->
<?=$this->partial('partial/admin/feedback/dialog.phtml')?>
<!-- /dialog2 -->

<?=$this->partial('partial/admin/js/validate.phtml')?>
<script type="text/javascript" src="/js/service/Toast.js"></script>
<script type="text/javascript" src="/js/manager/card.js"></script>