<?php $this->headTitle('银行卡错误');?>
<div class="page__bd">
    <div class="weui-form-preview">
        <div class="weui-msg">
            <div class="weui-msg__icon-area">
            	<i class="weui-icon-warn weui-icon_msg"></i>
        	</div>
            <div class="weui-msg__text-area">
                <h2 class="weui-msg__title">银行卡有误</h2>
                <p class="weui-msg__desc">操作超时或银行卡号错误，请重新输入(不支持信用卡绑定)!</p>
            </div>
            <div class="weui-msg__opr-area">
                <p class="weui-btn-area">
                    <a href="javascript:history.back();" class="weui-btn weui-btn_primary">重新填写</a>
                </p>
            </div>
        </div>
	</div>
</div>