<?php $this->headTitle('我的银行卡');?>
<div class="page__bd">
    <div class="weui-form-preview">
    	<?php if (!empty($this->item['card_no'])){?>
        <div class="weui-form-preview__hd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">银行卡号：</label>
            </div>
            <div class="weui-form-preview__item" style="text-align: left">
                <em class="weui-form-preview__value"><?=$this->item['card_no']?></em>
            </div>
        </div>
        <div class="weui-form-preview__bd">
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">发卡银行：</label>
                <span class="weui-form-preview__value"><?=$this->item['card_bank_name']?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">持卡人姓名：</label>
                <span class="weui-form-preview__value"><?=$this->item['card_user_name']?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">开户地区：</label>
                <span class="weui-form-preview__value"><?=$this->item['card_bank_area']?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">开户支行：</label>
                <span class="weui-form-preview__value"><?=$this->item['card_bank_branch_name']?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">卡片类型：</label>
                <span class="weui-form-preview__value"><?=$this->item['card_type_name']?></span>
            </div>
            <div class="weui-form-preview__item">
                <label class="weui-form-preview__label">手机号</label>
                <span class="weui-form-preview__value"><?=$this->item['card_user_tel']?></span>
            </div>
        </div>
        <?php }else {?>
        <div class="weui-msg">
        	<div class="weui-msg__icon-area">
        		<i class="weui-icon-waiting weui-icon_msg"></i>
        	</div>
        	<div class="weui-msg__text-area">
        		<h2 class="weui-msg__title">未添加银行卡</h2>
        	</div>
        </div>
        <?php }?>
        <div class="weui-form-preview__ft">
            <a class="weui-form-preview__btn weui-form-preview__btn_default" href="/withdraw">返回提现</a>
            <a class="weui-form-preview__btn weui-form-preview__btn_primary" href="/card/editFirst">修改银行卡</a>
        </div>
        <!-- 银行卡说明 -->
    	<div class="weui-media-box weui-media-box_text">
    		<h6 class="weui-media-box__title">银行卡用于</h6>
    		<p class="weui-media-box__desc">1.返现订单每月返现积分提现；</p>
    		<p class="weui-media-box__desc">2.分销员月度佣金提现；</p>
    		<p class="weui-media-box__desc">3.请确保银行卡正确无误；</p>
    	</div>
    	<!-- /银行卡说明 -->
    </div>
    <br>
</div>
