<?php
/**
 * 适用于table页面活着带有分页的table页面
 *  */
$pageName   = $this->pageName; // string
$pageTitle  = $this->pageTitle; // string
$formContent= $this->formContent;
$form_id    = $this->form_id;
$action     = $this->action;
$withBack   = $this->withBack;
$panelTitle = $this->panelTitle ? $this->panelTitle : $pageTitle;

/* used age

<?=$this->partial('partial/admin/page/form-page.phtml', [
'pageName'      => 'UserListPage',
'pageTitle'     => '用户管理',
'form_id'       =>'',
'action'        =>'',
'formContent'   => $this->placeholder('formContent'),
])?> 

*/

?>

<?php $this->placeholder('x_content')->captureStart();?>
<div class="x_content">
	<br />
	<?=$this->partial('partial/admin/form/form/form.phtml', [
	    'form_id'       => $form_id,
        'action'        => $action,
	    'withBack'      => $withBack !== false,
	    'formContent'   => $formContent,
	])?>
</div>
<?php $this->placeholder('x_content')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/basic-page.phtml', [
    'panelTitle'    => $panelTitle,
    'pageName'      => $pageName,
    'pageTitle'     => $pageTitle,
    'navbar'        => $this->navbar,
    'x_content'     => $this->placeholder('x_content'),
])?>
