<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<meta charset="UTF-8">
<meta name="viewport"
	content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
	<?=$this->headTitle('坦罕斯商城')->setSeparator(' - ') ?>
	<?=$this->partial('partial/admin/css/common.phtml'); ?>
<body ontouchstart>
	<script type="text/javascript" src="/vendor/zepto.min.js"></script>
	<div class="container" id="container">
		<div class="page js_show">
				<?=$this->content ?>
				<div class="page__ft weui-footer">
				<p class="weui-footer__text">Copyright © 2016-<?=date('Y')?> 呼和科技(北京)有限公司</p>
			</div>
		</div>
	</div>
</body>
<script src="https://res.wx.qq.com/open/js/jweixin-1.2.0.js"
	type="text/javascript"></script>
<script src="https://res.wx.qq.com/open/libs/weuijs/1.1.2/weui.min.js"
	type="text/javascript"></script>
<script src="/js/example.js"></script>
<script src="/js/menu.js"></script>
<script src="/js/service/Button.js"></script>
</html>