<?php 
$identity = $this->identity();
$workyard_id = $this->User()->getWorkyardId($identity);
?>
<?php $this->placeholder('formContent')->captureStart();?>
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '名称：',
	    'name' => 'name',
	    'placeholder' => '请输入名称',
	    'type' => 'text'
	])?>
	
	<?=$this->partial('partial/admin/form/input/input.phtml', [
	    'label' => '开始时间：',
	    'name' => 'start_time',
	    'placeholder' => '请输入开始时间',
	    'type' => 'text',
	    'class' => 'timepicker',
	])?>
	
	<?=$this->partial('admin/shift-type/partial/input-end-time.phtml', [
	    'is_next_day' => '',
	    'end_time' => '',
	])?>
	
    <?=$this->partial('partial/admin/form/input/input-hide.phtml', [
    'name'  => 'workyard_id',
    'value' => $workyard_id,
	])?>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/form-modal.phtml', [
    'pageName' => 'ShiftTypeAddModal',
    'pageTitle' => '新增班次',
    'modalSize'     => 'lg',
    'form_id'=>'form-add',
    'action'=>'/api/shiftType/add',
    'formContent' => $this->placeholder('formContent'),
])?>
