<?php 
$typeID     = $this->typeID;
$Entity     = $this->ShiftType()->getEntity($typeID);
$name       = $Entity->getName();

$token = $this->Token()->getToken();

?>

<?php $this->placeholder('formContent')->captureStart();?>
<p>确认删除 <?=$name?>?</p>
<p>不影响已安排的值班计划。</p>
<?php $this->placeholder('formContent')->captureEnd() ?>

<?=$this->partial('partial/admin/page/modal/delete-modal.phtml', [
    'pageName' => 'ShiftTypeDeleteModal',
    'pageTitle' => '删除',
    'form_id'=>'form-delete-shift-type',
    'action'=>"/api/shiftType/delete/$typeID?token=$token",
    'canDelete'=>true,
    'formContent' => $this->placeholder('formContent'),
])?>
