<?php 

$identity = $this->identity();
$where    = $this->where;
$workyard_id = $this->User()->getWorkyardId($identity);
$paginator = $this->ShiftType()->getPaginator($this->page, $where, $workyard_id);
?>
<?php $this->placeholder('buttonGroup')->captureStart();?>
<?=$this->partial('partial/admin/button/single.phtml', [
    'type'  => 'primary',
    'title' => '新增班次',
    'data_modal_open' => true,
    'data_modal_url' => '/shiftType/addModal'
])?>
<?php $this->placeholder('buttonGroup')->captureEnd() ?>

<?php $this->placeholder('table')->captureStart();?>
<table class="table table-striped jambo_table">
    <thead>
        <tr>
          <th >名称</th>
          <th >开始时间</th>
          <th >结束时间</th>
          <th >操作</th>
    	</tr>
    </thead>
      <tbody>
      	<?php if (count($paginator)) :?>
      		<?php foreach ($paginator as $Entity):?>
      		<?php 
      		$typeID = $Entity->getId();
      		$name   = $Entity->getName();
      		$start_time = $Entity->getStart_time();
      		$end_time   = $Entity->getEnd_time();
      		?>
      		<tr>
      		<td><?=$name?></td>
      		<td><?=$start_time?></td>
      		<td><?=$end_time?></td>
      		<td>
      		<div class="btn-group  btn-group-sm">
      		<?=$this->partial('partial/admin/button/single.phtml', [
                'title' => '编辑',
                'data_modal_open' => true,
      		    'data_modal_url' => '/shiftType/editModal/'.$typeID, //string
            ])?>
            </div>
      		</td>
            </tr>
      		<?php endforeach;?>
      	<?php endif;?>
      </tbody>
</table>
<?php $this->placeholder('table')->captureEnd() ?>

<?=$this->partial('partial/admin/page/page/table-page.phtml', [
    'pageName'      => 'UserListPage',
    'pageTitle'     => '巡检班次设置',
    'paginator'     => $paginator,
    'search'        => $where,
    'buttonGroup'   => $this->placeholder('buttonGroup'),
//     'searchContent' => $this->placeholder('searchContent'),
    'table'         => $this->placeholder('table'),
])?>
